### ISSUE TITLE
can't create dataset: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by walterwang** [balancap/SSD-Tensorflow#108]
I get this error when I attempt to create a dataset from VOC2012 and also a custom dataset:
tensorflow version is 1.2
Dataset directory: /media/walter/565EBE215EBDF9B7/VOCdevkit/head_VOC/
Output directory: /home/walter/Documents/others_git/tfrecords
>> Converting image 1/664Traceback (most recent call last):
  File "tf_convert_data.py", line 59, in <module>
    tf.app.run()
  File "/home/walter/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tf_convert_data.py", line 54, in main
    pascalvoc_to_tfrecords.run(FLAGS.dataset_dir, FLAGS.output_dir, FLAGS.output_name)
  File "/home/walter/Documents/others_git/SSD-Tensorflow/datasets/pascalvoc_to_tfrecords.py", line 218, in run
    _add_to_tfrecord(dataset_dir, img_name, tfrecord_writer)
  File "/home/walter/Documents/others_git/SSD-Tensorflow/datasets/pascalvoc_to_tfrecords.py", line 177, in _add_to_tfrecord
    _process_image(dataset_dir, name)
  File "/home/walter/Documents/others_git/SSD-Tensorflow/datasets/pascalvoc_to_tfrecords.py", line 83, in _process_image
    image_data = tf.gfile.FastGFile(filename, 'r').read()
  File "/home/walter/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/walter/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 93, in _prepare_value
    return compat.as_str_any(val)
  File "/home/walter/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/home/walter/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by walterwang** [comment]
fix:
pascalvoc_to_tfrecords.py
`
image_data = tf.gfile.FastGFile(filename, 'r').read()`
change that to:
`image_data = tf.gfile.FastGFile(filename, 'rb').read()`

**Comment by Nash2325138** [comment]
The answer above resolve my problem when running this:
https://github.com/tensorflow/models/tree/master/compression/image_encoder

Thanks!

**Comment by liruixl** [comment]
I want to know that's why?

**Comment by Hizhaoyuan** [comment]
@liruixl you can google it, there are some interpretations

**Comment by tricoffee** [comment]
> I want to know that's why?
For a Python 3 environment:
r: Python will parse according to the encoding format, and the read() function returns str
rb: that is, binary mode, the read() function returns bytes

**Comment by sakaia** [comment]
This problem still remain. It needs to fix. 
https://github.com/balancap/SSD-Tensorflow/blob/master/datasets/pascalvoc_to_tfrecords.py#L83
