### ISSUE TITLE
Training Instructions

### ISSUE THREAD

**Issue by alberto139** [balancap/SSD-Tensorflow#125]
Hello All,

I know that there are many issues regarding training but I was hopping we could compile some instructions as to how to train in a single place and perhaps have the detailed instructions added to the `README.md`.

**Step 0**:  Run the minimal example

Make sure you can run `ssd_notebook.ipynb`. This includes `unzip checkpoints/ssd_300_vgg.ckpt.zip` and` jupyter notebook notebooks/ssd_notebook.ipynb`

**Step 1**: Download the dataset and covert it to a tfrecord.

Personally, I got the Pascal VOC data from [here](https://pjreddie.com/projects/pascal-voc-dataset-mirror/). 

**Step 2**: create tfrecord

To make the tfrecord I ran the following command:
`python tf_convert_data.py     --dataset_name=pascalvoc     --dataset_dir=../VOCdevkit/VOC2007/     --output_name=pascalvoc     --output_dir=../tmp`

**Step 3**: Train
Run the following command:
`python3 train_ssd_network.py --dataset_dir=../tmp`

Here is were I get stuck...
Here is the output and traceback:

```
# # =========================================================================== #
# Training | Evaluation flags:
# =========================================================================== #
{'adadelta_rho': 0.95,
 'adagrad_initial_accumulator_value': 0.1,
 'adam_beta1': 0.9,
 'adam_beta2': 0.999,
 'batch_size': 32,
 'checkpoint_exclude_scopes': None,
 'checkpoint_model_scope': None,
 'checkpoint_path': None,
 'clone_on_cpu': False,
 'dataset_dir': '../tmp',
 'dataset_name': 'imagenet',
 'dataset_split_name': 'train',
 'end_learning_rate': 0.0001,
 'ftrl_initial_accumulator_value': 0.1,
 'ftrl_l1': 0.0,
 'ftrl_l2': 0.0,
 'ftrl_learning_rate_power': -0.5,
 'gpu_memory_fraction': 0.75,
 'ignore_missing_vars': False,
 'label_smoothing': 0.0,
 'labels_offset': 0,
 'learning_rate': 0.01,
 'learning_rate_decay_factor': 0.94,
 'learning_rate_decay_type': 'exponential',
 'log_every_n_steps': 10,
 'loss_alpha': 1.0,
 'match_threshold': 0.5,
 'max_number_of_steps': None,
 'model_name': 'ssd_300_vgg',
 'momentum': 0.9,
 'moving_average_decay': None,
 'negative_ratio': 3.0,
 'num_classes': 21,
 'num_clones': 1,
 'num_epochs_per_decay': 2.0,
 'num_preprocessing_threads': 4,
 'num_readers': 4,
 'opt_epsilon': 1.0,
 'optimizer': 'rmsprop',
 'preprocessing_name': None,
 'rmsprop_decay': 0.9,
 'rmsprop_momentum': 0.9,
 'save_interval_secs': 600,
 'save_summaries_secs': 600,
 'train_dir': '/tmp/tfmodel/',
 'train_image_size': None,
 'trainable_scopes': None,
 'weight_decay': 4e-05}

# =========================================================================== #
# SSD net parameters:
# =========================================================================== #
{'anchor_offset': 0.5,
 'anchor_ratios': [[2, 0.5],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5],
                   [2, 0.5]],
 'anchor_size_bounds': [0.15, 0.9],
 'anchor_sizes': [(21.0, 45.0),
                  (45.0, 99.0),
                  (99.0, 153.0),
                  (153.0, 207.0),
                  (207.0, 261.0),
                  (261.0, 315.0)],
 'anchor_steps': [8, 16, 32, 64, 100, 300],
 'feat_layers': ['block4', 'block7', 'block8', 'block9', 'block10', 'block11'],
 'feat_shapes': [(38, 38), (19, 19), (10, 10), (5, 5), (3, 3), (1, 1)],
 'img_shape': (300, 300),
 'no_annotation_label': 21,
 'normalizations': [20, -1, -1, -1, -1, -1],
 'num_classes': 21,
 'prior_scaling': [0.1, 0.1, 0.2, 0.2]}

# =========================================================================== #
# Training | Evaluation dataset files:
# ========================================================================== #
['../tmp/train-pascalvoc.tfrecord']

Traceback (most recent call last):
  File "train_ssd_network.py", line 385, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 232, in main
    'object/bbox'])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/data_provider.py", line 79, in get
    self._validate_items(items)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/data_provider.py", line 115, in _validate_items
    (item, valid_items))
ValueError: Item [shape] is invalid. Valid entries include: dict_keys(['image', 'label', 'label_text', 'object/bbox', 'object/label', 'record_key'])

```

Not really sure what is going on here. I think it has to do with the way the data is structured.
Any help with my problem or completing the training instructions is greatly appreciated!!

**Comment by Mudwall** [comment]
I have the same problem.Have you solved it?

**Comment by alberto139** [comment]
@Mudwall I haven't solved it yet. I'll update as soon as I do.

**Comment by iron-fe** [comment]
@alberto139 
In train_ssd_network.py, at line 232,
you can change this             
`[image, shape, glabels, gbboxes] = provider.get(['image', 'shape',
                                                             'object/label',
                                                             'object/bbox'])`
to
` image, glabels, gbboxes] = provider.get(['image',
                                                 'object/label',
                                                 'object/bbox'])`

**Comment by alberto139** [comment]
@iron-fe 
That fixed the issue. Thanks!
