### ISSUE TITLE
how to use this mode to train my own data?

### ISSUE THREAD

**Issue by chunji96** [balancap/SSD-Tensorflow#126]
>１、what should be put in "./VOC2007/test/"?

>２、I have downloaded the model and extracted it,the name is "VGG_VOC0712_SSD_512x512_ft_iter_120000.ckpt.data-00000-of-00001",show I rename it to "VGG_VOC0712_SSD_512x512_ft_iter_120000.ckpt"？

>３、If I want to train my own data,what files should I change ? which format should my data be to convert to TF-Records?

>I am not good at English,so can not understand clearly about the steps of the whole precess to train my own data,thanks.

**Comment by HoracceFeng** [comment]
Hi, the /VOC2007/test is a dataset that you should download in another website. Just search PASCAL VOC. After download and unzip the file, put the "Annotations" and "JPEGimages" files into the /VOC2007/test.

As the second question, you don't have to rename the ckpt file. Just let it goes. You can do some search for the meaning of these documents. 

If you want to train your own data, you best first try the tutorial step by step, then I bet you know how to do next.

Best.

**Comment by chunji96** [comment]
Thank you for your  answer,I tried to put the right format of directories and files into /VOC2007/test,but result in some error when i convert the file,i will show you  tomorrow.
Appreciate.

**Comment by chunji96** [comment]
#### some errors occur,I think it maybe encoding problem.

> Converting image 1/5011Traceback (most recent call last):
  File "tf_convert_data.py", line 59, in <module>
    tf.app.run()
  File "/home/chanji/.conda/envs/ame/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tf_convert_data.py", line 54, in main
    pascalvoc_to_tfrecords.run(FLAGS.dataset_dir, FLAGS.output_dir, FLAGS.output_name)
  File "/home/chanji/project/deeplearning/SSD-Tensorflow/datasets/pascalvoc_to_tfrecords.py", line 218, in run
    _add_to_tfrecord(dataset_dir, img_name, tfrecord_writer)
  File "/home/chanji/project/deeplearning/SSD-Tensorflow/datasets/pascalvoc_to_tfrecords.py", line 177, in _add_to_tfrecord
    _process_image(dataset_dir, name)
  File "/home/chanji/project/deeplearning/SSD-Tensorflow/datasets/pascalvoc_to_tfrecords.py", line 83, in _process_image
    image_data = tf.gfile.FastGFile(filename, 'r').read()
  File "/home/chanji/.conda/envs/ame/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 122, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/chanji/.conda/envs/ame/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 90, in _prepare_value
    return compat.as_str_any(val)
  File "/home/chanji/.conda/envs/ame/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/home/chanji/.conda/envs/ame/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

#### how can  solve it?
thanks.

**Comment by gul98** [comment]
after training my own model on my own dataset. I am getting 0 accuracy during evaluation.
how can i solve it.

**Comment by chunji96** [comment]
@gul98
### I  have not tried my own datasets,I use the voc 2007，and the result is normal,but I met a error again.
![2017-09-01 21-22-28](https://user-images.githubusercontent.com/22830268/30000980-d97f7b9a-9044-11e7-8ddb-de786e10aec4.png)

do you known how to deal  with it ?

**Comment by HoracceFeng** [comment]
@jChanJi For the question you have asked previously, the error is from "tf.gfile.FastGFile(filename, 'r').read()", because of the difference of py2 and py3. I guess you have fixed it. 

For the question you have just asked, the problem is that you have to change the "data_format/; from NCHW to NHWC in "train.py". As for the reason, it would be better for you to read the source code.

BTW, I have gave up using this code. The author really did a good job, but it still not easy to use, plus, it actually cannot be used to train those model that different from VOC dataset. I strongly recommend you to use the "tensorflow/model/object_detection" module. That API have more stable and powerful performance.

**Comment by chunji96** [comment]
@HoracceFeng 
I hava find the problem,the version of tensorflow is not gpu version,thank you  to the same.because Graduation project teacher ask me to use this to detection the images ,so I have no chhoices to use this.

**Comment by seasonyang** [comment]
@jChanJi you can use the tool [here](https://github.com/hyzhan/make_own_dataset) to make your own data to pascal VOC format.

Then enjoy it!

**Comment by ArtlyStyles** [comment]
@jChanJi 

How did you fixed this problem? 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
