### ISSUE TITLE
Invalid argument: slice index 0 of dimension 0 out of bounds.

### ISSUE THREAD

**Issue by gul98** [balancap/SSD-Tensorflow#128]
Whenever i run evaluation using 
python eval_ssd_network.py \
    --eval_dir=${EVAL_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=test \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --batch_size=1

on my personal dataset after training. It gives this error

 evaluation at 2017-08-31-00:13:37
2017-08-31 05:13:39.065375: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-08-31 05:13:39.071712: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.14GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-08-31 05:13:39.071737: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-08-31 05:13:39.082630: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.37GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-08-31 05:13:39.096717: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.18GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-08-31 05:13:39.096744: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.37GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-08-31 05:13:39.222565: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-08-31 05:13:39.262334: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.262336: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.262590: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.262663: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3 = StridedSlice[Index=DT_INT32, T=DT_BOOL, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/Enter, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_1, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_2)]]
2017-08-31 05:13:39.262385: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.262830: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3 = StridedSlice[Index=DT_INT32, T=DT_BOOL, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/Enter, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_1, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_2)]]
2017-08-31 05:13:39.262337: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.262347: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263030: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263228: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263360: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263448: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263493: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3 = StridedSlice[Index=DT_INT32, T=DT_BOOL, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/Enter, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_1, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_2)]]
2017-08-31 05:13:39.263618: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263713: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263757: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263872: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263936: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.263957: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.264342: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.264389: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.264717: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-08-31 05:13:39.264817: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: slice index 0 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "eval_ssd_network.py", line 346, in <module>
    tf.app.run()
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 342, in main
    timeout=None)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/evaluation.py", line 285, in evaluation_loop
    timeout=timeout)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/evaluation.py", line 450, in evaluate_repeatedly
    session.run(eval_ops, feed_dict)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 484, in run
    run_metadata=run_metadata)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 820, in run
    run_metadata=run_metadata)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 930, in run
    run_metadata=run_metadata)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 776, in run
    return self._sess.run(*args, **kwargs)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3 = StridedSlice[Index=DT_INT32, T=DT_BOOL, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/Enter, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_1, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_2)]]
	 [[Node: ssd_losses/TopKV2/_553 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_10608_ssd_losses/TopKV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3', defined at:
  File "eval_ssd_network.py", line 346, in <module>
    tf.app.run()
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 207, in main
    matching_threshold=FLAGS.matching_threshold)
  File "/home2/gulzain/SSDTensorflow/tf_extended/bboxes.py", line 363, in bboxes_matching_batch
    matching_threshold)
  File "/home2/gulzain/SSDTensorflow/tf_extended/bboxes.py", line 379, in bboxes_matching_batch
    infer_shape=True)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "/home2/gulzain/SSDTensorflow/tf_extended/bboxes.py", line 373, in <lambda>
    matching_threshold),
  File "/home2/gulzain/SSDTensorflow/tf_extended/bboxes.py", line 322, in bboxes_matching
    back_prop=False)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home2/gulzain/SSDTensorflow/tf_extended/bboxes.py", line 300, in m_body
    not_difficult = tf.logical_not(gdifficults[idxmax])
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 497, in _SliceHelper
    name=name)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 655, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3568, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/umerjaved/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): slice index 0 of dimension 0 out of bounds.
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3 = StridedSlice[Index=DT_INT32, T=DT_BOOL, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/Enter, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_1, bboxes_matching_batch_dict/bboxes_matching_batch_5/map/while/bboxes_matching_single/while/strided_slice_3/stack_2)]]
	 [[Node: ssd_losses/TopKV2/_553 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_10608_ssd_losses/TopKV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Any idea where i am wrong?

**Comment by ivyteng** [comment]
Have you solved the problem? how to fix it?

Thanks

**Comment by freedomsb** [comment]
I get the same problem and I find that these errors happened when I cannot detect anything in a image using my trained model. For the pictures where I can detect things, the evaluation function works properly
