### ISSUE TITLE
RuntimeError: Init operations did not make model ready.  Init op: init_ops/init, init fn: None, local_init_op: name: "init_ops/group_deps

### ISSUE THREAD

**Issue by ziyeshanwai** [balancap/SSD-Tensorflow#140]
2017-09-25 00:09:25.111761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-09-25 00:09:25.111772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-09-25 00:09:25.111786: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.RuntimeError'>, Init operations did not make model ready.  Init op: init_ops/init, init fn: None, local_init_op: name: "init_ops/group_deps"
op: "NoOp"
input: "^init_ops/init_1"
input: "^init_ops/init_all_tables"
, error: Variables not initialized: global_step, ssd_300_vgg/conv1/conv1_1/weights, ssd_300_vgg/conv1/conv1_1/biases, ssd_300_vgg/conv1/conv1_2/weights, ssd_300_vgg/conv1/conv1_2/biases, ssd_300_vgg/conv2/conv2_1/weights, ssd_300_vgg/conv2/conv2_1/biases, ssd_300_vgg/conv2/conv2_2/weights, ssd_300_vgg/conv2/conv2_2/biases, ssd_300_vgg/conv3/conv3_1/weights, ssd_300_vgg/conv3/conv3_1/biases, ssd_300_vgg/conv3/conv3_2/weights, ssd_300_vgg/conv3/conv3_2/biases, ssd_300_vgg/conv3/conv3_3/weights, ssd_300_vgg/conv3/conv3_3/biases, ssd_300_vgg/conv4/conv4_1/weights, ssd_300_vgg/conv4/conv4_1/biases, ssd_300_vgg/conv4/conv4_2/weights, ssd_300_vgg/conv4/conv4_2/biases, ssd_300_vgg/conv4/conv4_3/weights, ssd_300_vgg/conv4/conv4_3/biases, ssd_300_vgg/conv5/conv5_1/weights, ssd_300_vgg/conv5/conv5_1/biases, ssd_300_vgg/conv5/conv5_2/weights, ssd_300_vgg/conv5/conv5_2/biases, ssd_300_vgg/conv5/conv5_3/weights, ssd_300_vgg/conv5/conv5_3/biases, ssd_300_vgg/conv6/weights, ssd_300_vgg/conv6/biases, ssd_300_vgg/conv7/weights, ssd_300_vgg/conv7/biases, ssd_300_vgg/block8/conv1x1/weights, ssd_300_vgg/block8/conv1x1/biases, ssd_300_vgg/block8/conv3x3/weights, ssd_300_vgg/block8/conv3x3/biases, ssd_300_vgg/block9/conv1x1/weights, ssd_300_vgg/block9/conv1x1/biases, ssd_300_vgg/block9/conv3x3/weights, ssd_300_vgg/block9/conv3x3/biases, ssd_300_vgg/block10/conv1x1/weights, ssd_300_vgg/block10/conv1x1/biases, ssd_300_vgg/block10/conv3x3/weights, ssd_300_vgg/block10/conv3x3/biases, ssd_300_vgg/block11/conv1x1/weights, ssd_300_vgg/block11/conv1x1/biases, ssd_300_vgg/block11/conv3x3/weights, ssd_300_vgg/block11/conv3x3/biases, ssd_300_vgg/block4_box/L2Normalization/gamma, ssd_300_vgg/block4_box/conv_loc/weights, ssd_300_vgg/block4_box/conv_loc/biases, ssd_300_vgg/block4_box/conv_cls/weights, ssd_300_vgg/block4_box/conv_cls/biases, ssd_300_vgg/block7_box/conv_loc/weights, ssd_300_vgg/block7_box/conv_loc/biases, ssd_300_vgg/block7_box/conv_cls/weights, ssd_300_vgg/block7_box/conv_cls/biases, ssd_300_vgg/block8_box/conv_loc/weights, ssd_300_vgg/block8_box/conv_loc/biases, ssd_300_vgg/block8_box/conv_cls/weights, ssd_300_vgg/block8_box/conv_cls/biases, ssd_300_vgg/block9_box/conv_loc/weights, ssd_300_vgg/block9_box/conv_loc/biases, ssd_300_vgg/block9_box/conv_cls/weights, ssd_300_vgg/block9_box/conv_cls/biases, ssd_300_vgg/block10_box/conv_loc/weights, ssd_300_vgg/block10_box/conv_loc/biases, ssd_300_vgg/block10_box/conv_cls/weights, ssd_300_vgg/block10_box/conv_cls/biases, ssd_300_vgg/block11_box/conv_loc/weights, ssd_300_vgg/block11_box/conv_loc/biases, ssd_300_vgg/block11_box/conv_cls/weights, ssd_300_vgg/block11_box/conv_cls/biases, beta1_power, beta2_power, ssd_300_vgg/conv1/conv1_1/weights/Adam, ssd_300_vgg/conv1/conv1_1/weights/Adam_1, ssd_300_vgg/conv1/conv1_1/biases/Adam, ssd_300_vgg/conv1/conv1_1/biases/Adam_1, ssd_300_vgg/conv1/conv1_2/weights/Adam, ssd_300_vgg/conv1/conv1_2/weights/Adam_1, ssd_300_vgg/conv1/conv1_2/biases/Adam, ssd_300_vgg/conv1/conv1_2/biases/Adam_1, ssd_300_vgg/conv2/conv2_1/weights/Adam, ssd_300_vgg/conv2/conv2_1/weights/Adam_1, ssd_300_vgg/conv2/conv2_1/biases/Adam, ssd_300_vgg/conv2/conv2_1/biases/Adam_1, ssd_300_vgg/conv2/conv2_2/weights/Adam, ssd_300_vgg/conv2/conv2_2/weights/Adam_1, ssd_300_vgg/conv2/conv2_2/biases/Adam, ssd_300_vgg/conv2/conv2_2/biases/Adam_1, ssd_300_vgg/conv3/conv3_1/weights/Adam, ssd_300_vgg/conv3/conv3_1/weights/Adam_1, ssd_300_vgg/conv3/conv3_1/biases/Adam, ssd_300_vgg/conv3/conv3_1/biases/Adam_1, ssd_300_vgg/conv3/conv3_2/weights/Adam, ssd_300_vgg/conv3/conv3_2/weights/Adam_1, ssd_300_vgg/conv3/conv3_2/biases/Adam, ssd_300_vgg/conv3/conv3_2/biases/Adam_1, ssd_300_vgg/conv3/conv3_3/weights/Adam, ssd_300_vgg/conv3/conv3_3/weights/Adam_1, ssd_300_vgg/conv3/conv3_3/biases/Adam, ssd_300_vgg/conv3/conv3_3/biases/Adam_1, ssd_300_vgg/conv4/conv4_1/weights/Adam, ssd_300_vgg/conv4/conv4_1/weights/Adam_1, ssd_300_vgg/conv4/conv4_1/biases/Adam, ssd_300_vgg/conv4/conv4_1/biases/Adam_1, ssd_300_vgg/conv4/conv4_2/weights/Adam, ssd_300_vgg/conv4/conv4_2/weights/Adam_1, ssd_300_vgg/conv4/conv4_2/biases/Adam, ssd_300_vgg/conv4/conv4_2/biases/Adam_1, ssd_300_vgg/conv4/conv4_3/weights/Adam, ssd_300_vgg/conv4/conv4_3/weights/Adam_1, ssd_300_vgg/conv4/conv4_3/biases/Adam, ssd_300_vgg/conv4/conv4_3/biases/Adam_1, ssd_300_vgg/conv5/conv5_1/weights/Adam, ssd_300_vgg/conv5/conv5_1/weights/Adam_1, ssd_300_vgg/conv5/conv5_1/biases/Adam, ssd_300_vgg/conv5/conv5_1/biases/Adam_1, ssd_300_vgg/conv5/conv5_2/weights/Adam, ssd_300_vgg/conv5/conv5_2/weights/Adam_1, ssd_300_vgg/conv5/conv5_2/biases/Adam, ssd_300_vgg/conv5/conv5_2/biases/Adam_1, ssd_300_vgg/conv5/conv5_3/weights/Adam, ssd_300_vgg/conv5/conv5_3/weights/Adam_1, ssd_300_vgg/conv5/conv5_3/biases/Adam, ssd_300_vgg/conv5/conv5_3/biases/Adam_1, ssd_300_vgg/conv6/weights/Adam, ssd_300_vgg/conv6/weights/Adam_1, ssd_300_vgg/conv6/biases/Adam, ssd_300_vgg/conv6/biases/Adam_1, ssd_300_vgg/conv7/weights/Adam, ssd_300_vgg/conv7/weights/Adam_1, ssd_300_vgg/conv7/biases/Adam, ssd_300_vgg/conv7/biases/Adam_1, ssd_300_vgg/block8/conv1x1/weights/Adam, ssd_300_vgg/block8/conv1x1/weights/Adam_1, ssd_300_vgg/block8/conv1x1/biases/Adam, ssd_300_vgg/block8/conv1x1/biases/Adam_1, ssd_300_vgg/block8/conv3x3/weights/Adam, ssd_300_vgg/block8/conv3x3/weights/Adam_1, ssd_300_vgg/block8/conv3x3/biases/Adam, ssd_300_vgg/block8/conv3x3/biases/Adam_1, ssd_300_vgg/block9/conv1x1/weights/Adam, ssd_300_vgg/block9/conv1x1/weights/Adam_1, ssd_300_vgg/block9/conv1x1/biases/Adam, ssd_300_vgg/block9/conv1x1/biases/Adam_1, ssd_300_vgg/block9/conv3x3/weights/Adam, ssd_300_vgg/block9/conv3x3/weights/Adam_1, ssd_300_vgg/block9/conv3x3/biases/Adam, ssd_300_vgg/block9/conv3x3/biases/Adam_1, ssd_300_vgg/block10/conv1x1/weights/Adam, ssd_300_vgg/block10/conv1x1/weights/Adam_1, ssd_300_vgg/block10/conv1x1/biases/Adam, ssd_300_vgg/block10/conv1x1/biases/Adam_1, ssd_300_vgg/block10/conv3x3/weights/Adam, ssd_300_vgg/block10/conv3x3/weights/Adam_1, ssd_300_vgg/block10/conv3x3/biases/Adam, ssd_300_vgg/block10/conv3x3/biases/Adam_1, ssd_300_vgg/block11/conv1x1/weights/Adam, ssd_300_vgg/block11/conv1x1/weights/Adam_1, ssd_300_vgg/block11/conv1x1/biases/Adam, ssd_300_vgg/block11/conv1x1/biases/Adam_1, ssd_300_vgg/block11/conv3x3/weights/Adam, ssd_300_vgg/block11/conv3x3/weights/Adam_1, ssd_300_vgg/block11/conv3x3/biases/Adam, ssd_300_vgg/block11/conv3x3/biases/Adam_1, ssd_300_vgg/block4_box/L2Normalization/gamma/Adam, ssd_300_vgg/block4_box/L2Normalization/gamma/Adam_1, ssd_300_vgg/block4_box/conv_loc/weights/Adam, ssd_300_vgg/block4_box/conv_loc/weights/Adam_1, ssd_300_vgg/block4_box/conv_loc/biases/Adam, ssd_300_vgg/block4_box/conv_loc/biases/Adam_1, ssd_300_vgg/block4_box/conv_cls/weights/Adam, ssd_300_vgg/block4_box/conv_cls/weights/Adam_1, ssd_300_vgg/block4_box/conv_cls/biases/Adam, ssd_300_vgg/block4_box/conv_cls/biases/Adam_1, ssd_300_vgg/block7_box/conv_loc/weights/Adam, ssd_300_vgg/block7_box/conv_loc/weights/Adam_1, ssd_300_vgg/block7_box/conv_loc/biases/Adam, ssd_300_vgg/block7_box/conv_loc/biases/Adam_1, ssd_300_vgg/block7_box/conv_cls/weights/Adam, ssd_300_vgg/block7_box/conv_cls/weights/Adam_1, ssd_300_vgg/block7_box/conv_cls/biases/Adam, ssd_300_vgg/block7_box/conv_cls/biases/Adam_1, ssd_300_vgg/block8_box/conv_loc/weights/Adam, ssd_300_vgg/block8_box/conv_loc/weights/Adam_1, ssd_300_vgg/block8_box/conv_loc/biases/Adam, ssd_300_vgg/block8_box/conv_loc/biases/Adam_1, ssd_300_vgg/block8_box/conv_cls/weights/Adam, ssd_300_vgg/block8_box/conv_cls/weights/Adam_1, ssd_300_vgg/block8_box/conv_cls/biases/Adam, ssd_300_vgg/block8_box/conv_cls/biases/Adam_1, ssd_300_vgg/block9_box/conv_loc/weights/Adam, ssd_300_vgg/block9_box/conv_loc/weights/Adam_1, ssd_300_vgg/block9_box/conv_loc/biases/Adam, ssd_300_vgg/block9_box/conv_loc/biases/Adam_1, ssd_300_vgg/block9_box/conv_cls/weights/Adam, ssd_300_vgg/block9_box/conv_cls/weights/Adam_1, ssd_300_vgg/block9_box/conv_cls/biases/Adam, ssd_300_vgg/block9_box/conv_cls/biases/Adam_1, ssd_300_vgg/block10_box/conv_loc/weights/Adam, ssd_300_vgg/block10_box/conv_loc/weights/Adam_1, ssd_300_vgg/block10_box/conv_loc/biases/Adam, ssd_300_vgg/block10_box/conv_loc/biases/Adam_1, ssd_300_vgg/block10_box/conv_cls/weights/Adam, ssd_300_vgg/block10_box/conv_cls/weights/Adam_1, ssd_300_vgg/block10_box/conv_cls/biases/Adam, ssd_300_vgg/block10_box/conv_cls/biases/Adam_1, ssd_300_vgg/block11_box/conv_loc/weights/Adam, ssd_300_vgg/block11_box/conv_loc/weights/Adam_1, ssd_300_vgg/block11_box/conv_loc/biases/Adam, ssd_300_vgg/block11_box/conv_loc/biases/Adam_1, ssd_300_vgg/block11_box/conv_cls/weights/Adam, ssd_300_vgg/block11_box/conv_cls/weights/Adam_1, ssd_300_vgg/block11_box/conv_cls/biases/Adam, ssd_300_vgg/block11_box/conv_cls/biases/Adam_1
Traceback (most recent call last):
  File "train_ssd_network.py", line 404, in <module>
    tf.app.run()
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 398, in main
    sync_optimizer=None)
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 725, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/home/liyouwang/anaconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 788, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 949, in managed_session
    start_standard_services=start_standard_services)
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 706, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/liyouwang/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 287, in prepare_session
    self._local_init_op, msg))
RuntimeError: Init operations did not make model ready.  Init op: init_ops/init, init fn: None, local_init_op: name: "init_ops/group_deps"
op: "NoOp"
input: "^init_ops/init_1"
input: "^init_ops/init_all_tables"
, error: Variables not initialized: global_step, ssd_300_vgg/conv1/conv1_1/weights, ssd_300_vgg/conv1/conv1_1/biases, ssd_300_vgg/conv1/conv1_2/weights, ssd_300_vgg/conv1/conv1_2/biases, ssd_300_vgg/conv2/conv2_1/weights, ssd_300_vgg/conv2/conv2_1/biases, ssd_300_vgg/conv2/conv2_2/weights, ssd_300_vgg/conv2/conv2_2/biases, ssd_300_vgg/conv3/conv3_1/weights, ssd_300_vgg/conv3/conv3_1/biases, ssd_300_vgg/conv3/conv3_2/weights, ssd_300_vgg/conv3/conv3_2/biases, ssd_300_vgg/conv3/conv3_3/weights, ssd_300_vgg/conv3/conv3_3/biases, ssd_300_vgg/conv4/conv4_1/weights, ssd_300_vgg/conv4/conv4_1/biases, ssd_300_vgg/conv4/conv4_2/weights, ssd_300_vgg/conv4/conv4_2/biases, ssd_300_vgg/conv4/conv4_3/weights, ssd_300_vgg/conv4/conv4_3/biases, ssd_300_vgg/conv5/conv5_1/weights, ssd_300_vgg/conv5/conv5_1/biases, ssd_300_vgg/conv5/conv5_2/weights, ssd_300_vgg/conv5/conv5_2/biases, ssd_300_vgg/conv5/conv5_3/weights, ssd_300_vgg/conv5/conv5_3/biases, ssd_300_vgg/conv6/weights, ssd_300_vgg/conv6/biases, ssd_300_vgg/conv7/weights, ssd_300_vgg/conv7/biases, ssd_300_vgg/block8/conv1x1/weights, ssd_300_vgg/block8/conv1x1/biases, ssd_300_vgg/block8/conv3x3/weights, ssd_300_vgg/block8/conv3x3/biases, ssd_300_vgg/block9/conv1x1/weights, ssd_300_vgg/block9/conv1x1/biases, ssd_300_vgg/block9/conv3x3/weights, ssd_300_vgg/block9/conv3x3/biases, ssd_300_vgg/block10/conv1x1/weights, ssd_300_vgg/block10/conv1x1/biases, ssd_300_vgg/block10/conv3x3/weights, ssd_300_vgg/block10/conv3x3/biases, ssd_300_vgg/block11/conv1x1/weights, ssd_300_vgg/block11/conv1x1/biases, ssd_300_vgg/block11/conv3x3/weights, ssd_300_vgg/block11/conv3x3/biases, ssd_300_vgg/block4_box/L2Normalization/gamma, ssd_300_vgg/block4_box/conv_loc/weights, ssd_300_vgg/block4_box/conv_loc/biases, ssd_300_vgg/block4_box/conv_cls/weights, ssd_300_vgg/block4_box/conv_cls/biases, ssd_300_vgg/block7_box/conv_loc/weights, ssd_300_vgg/block7_box/conv_loc/biases, ssd_300_vgg/block7_box/conv_cls/weights, ssd_300_vgg/block7_box/conv_cls/biases, ssd_300_vgg/block8_box/conv_loc/weights, ssd_300_vgg/block8_box/conv_loc/biases, ssd_300_vgg/block8_box/conv_cls/weights, ssd_300_vgg/block8_box/conv_cls/biases, ssd_300_vgg/block9_box/conv_loc/weights, ssd_300_vgg/block9_box/conv_loc/biases, ssd_300_vgg/block9_box/conv_cls/weights, ssd_300_vgg/block9_box/conv_cls/biases, ssd_300_vgg/block10_box/conv_loc/weights, ssd_300_vgg/block10_box/conv_loc/biases, ssd_300_vgg/block10_box/conv_cls/weights, ssd_300_vgg/block10_box/conv_cls/biases, ssd_300_vgg/block11_box/conv_loc/weights, ssd_300_vgg/block11_box/conv_loc/biases, ssd_300_vgg/block11_box/conv_cls/weights, ssd_300_vgg/block11_box/conv_cls/biases, beta1_power, beta2_power, ssd_300_vgg/conv1/conv1_1/weights/Adam, ssd_300_vgg/conv1/conv1_1/weights/Adam_1, ssd_300_vgg/conv1/conv1_1/biases/Adam, ssd_300_vgg/conv1/conv1_1/biases/Adam_1, ssd_300_vgg/conv1/conv1_2/weights/Adam, ssd_300_vgg/conv1/conv1_2/weights/Adam_1, ssd_300_vgg/conv1/conv1_2/biases/Adam, ssd_300_vgg/conv1/conv1_2/biases/Adam_1, ssd_300_vgg/conv2/conv2_1/weights/Adam, ssd_300_vgg/conv2/conv2_1/weights/Adam_1, ssd_300_vgg/conv2/conv2_1/biases/Adam, ssd_300_vgg/conv2/conv2_1/biases/Adam_1, ssd_300_vgg/conv2/conv2_2/weights/Adam, ssd_300_vgg/conv2/conv2_2/weights/Adam_1, ssd_300_vgg/conv2/conv2_2/biases/Adam, ssd_300_vgg/conv2/conv2_2/biases/Adam_1, ssd_300_vgg/conv3/conv3_1/weights/Adam, ssd_300_vgg/conv3/conv3_1/weights/Adam_1, ssd_300_vgg/conv3/conv3_1/biases/Adam, ssd_300_vgg/conv3/conv3_1/biases/Adam_1, ssd_300_vgg/conv3/conv3_2/weights/Adam, ssd_300_vgg/conv3/conv3_2/weights/Adam_1, ssd_300_vgg/conv3/conv3_2/biases/Adam, ssd_300_vgg/conv3/conv3_2/biases/Adam_1, ssd_300_vgg/conv3/conv3_3/weights/Adam, ssd_300_vgg/conv3/conv3_3/weights/Adam_1, ssd_300_vgg/conv3/conv3_3/biases/Adam, ssd_300_vgg/conv3/conv3_3/biases/Adam_1, ssd_300_vgg/conv4/conv4_1/weights/Adam, ssd_300_vgg/conv4/conv4_1/weights/Adam_1, ssd_300_vgg/conv4/conv4_1/biases/Adam, ssd_300_vgg/conv4/conv4_1/biases/Adam_1, ssd_300_vgg/conv4/conv4_2/weights/Adam, ssd_300_vgg/conv4/conv4_2/weights/Adam_1, ssd_300_vgg/conv4/conv4_2/biases/Adam, ssd_300_vgg/conv4/conv4_2/biases/Adam_1, ssd_300_vgg/conv4/conv4_3/weights/Adam, ssd_300_vgg/conv4/conv4_3/weights/Adam_1, ssd_300_vgg/conv4/conv4_3/biases/Adam, ssd_300_vgg/conv4/conv4_3/biases/Adam_1, ssd_300_vgg/conv5/conv5_1/weights/Adam, ssd_300_vgg/conv5/conv5_1/weights/Adam_1, ssd_300_vgg/conv5/conv5_1/biases/Adam, ssd_300_vgg/conv5/conv5_1/biases/Adam_1, ssd_300_vgg/conv5/conv5_2/weights/Adam, ssd_300_vgg/conv5/conv5_2/weights/Adam_1, ssd_300_vgg/conv5/conv5_2/biases/Adam, ssd_300_vgg/conv5/conv5_2/biases/Adam_1, ssd_300_vgg/conv5/conv5_3/weights/Adam, ssd_300_vgg/conv5/conv5_3/weights/Adam_1, ssd_300_vgg/conv5/conv5_3/biases/Adam, ssd_300_vgg/conv5/conv5_3/biases/Adam_1, ssd_300_vgg/conv6/weights/Adam, ssd_300_vgg/conv6/weights/Adam_1, ssd_300_vgg/conv6/biases/Adam, ssd_300_vgg/conv6/biases/Adam_1, ssd_300_vgg/conv7/weights/Adam, ssd_300_vgg/conv7/weights/Adam_1, ssd_300_vgg/conv7/biases/Adam, ssd_300_vgg/conv7/biases/Adam_1, ssd_300_vgg/block8/conv1x1/weights/Adam, ssd_300_vgg/block8/conv1x1/weights/Adam_1, ssd_300_vgg/block8/conv1x1/biases/Adam, ssd_300_vgg/block8/conv1x1/biases/Adam_1, ssd_300_vgg/block8/conv3x3/weights/Adam, ssd_300_vgg/block8/conv3x3/weights/Adam_1, ssd_300_vgg/block8/conv3x3/biases/Adam, ssd_300_vgg/block8/conv3x3/biases/Adam_1, ssd_300_vgg/block9/conv1x1/weights/Adam, ssd_300_vgg/block9/conv1x1/weights/Adam_1, ssd_300_vgg/block9/conv1x1/biases/Adam, ssd_300_vgg/block9/conv1x1/biases/Adam_1, ssd_300_vgg/block9/conv3x3/weights/Adam, ssd_300_vgg/block9/conv3x3/weights/Adam_1, ssd_300_vgg/block9/conv3x3/biases/Adam, ssd_300_vgg/block9/conv3x3/biases/Adam_1, ssd_300_vgg/block10/conv1x1/weights/Adam, ssd_300_vgg/block10/conv1x1/weights/Adam_1, ssd_300_vgg/block10/conv1x1/biases/Adam, ssd_300_vgg/block10/conv1x1/biases/Adam_1, ssd_300_vgg/block10/conv3x3/weights/Adam, ssd_300_vgg/block10/conv3x3/weights/Adam_1, ssd_300_vgg/block10/conv3x3/biases/Adam, ssd_300_vgg/block10/conv3x3/biases/Adam_1, ssd_300_vgg/block11/conv1x1/weights/Adam, ssd_300_vgg/block11/conv1x1/weights/Adam_1, ssd_300_vgg/block11/conv1x1/biases/Adam, ssd_300_vgg/block11/conv1x1/biases/Adam_1, ssd_300_vgg/block11/conv3x3/weights/Adam, ssd_300_vgg/block11/conv3x3/weights/Adam_1, ssd_300_vgg/block11/conv3x3/biases/Adam, ssd_300_vgg/block11/conv3x3/biases/Adam_1, ssd_300_vgg/block4_box/L2Normalization/gamma/Adam, ssd_300_vgg/block4_box/L2Normalization/gamma/Adam_1, ssd_300_vgg/block4_box/conv_loc/weights/Adam, ssd_300_vgg/block4_box/conv_loc/weights/Adam_1, ssd_300_vgg/block4_box/conv_loc/biases/Adam, ssd_300_vgg/block4_box/conv_loc/biases/Adam_1, ssd_300_vgg/block4_box/conv_cls/weights/Adam, ssd_300_vgg/block4_box/conv_cls/weights/Adam_1, ssd_300_vgg/block4_box/conv_cls/biases/Adam, ssd_300_vgg/block4_box/conv_cls/biases/Adam_1, ssd_300_vgg/block7_box/conv_loc/weights/Adam, ssd_300_vgg/block7_box/conv_loc/weights/Adam_1, ssd_300_vgg/block7_box/conv_loc/biases/Adam, ssd_300_vgg/block7_box/conv_loc/biases/Adam_1, ssd_300_vgg/block7_box/conv_cls/weights/Adam, ssd_300_vgg/block7_box/conv_cls/weights/Adam_1, ssd_300_vgg/block7_box/conv_cls/biases/Adam, ssd_300_vgg/block7_box/conv_cls/biases/Adam_1, ssd_300_vgg/block8_box/conv_loc/weights/Adam, ssd_300_vgg/block8_box/conv_loc/weights/Adam_1, ssd_300_vgg/block8_box/conv_loc/biases/Adam, ssd_300_vgg/block8_box/conv_loc/biases/Adam_1, ssd_300_vgg/block8_box/conv_cls/weights/Adam, ssd_300_vgg/block8_box/conv_cls/weights/Adam_1, ssd_300_vgg/block8_box/conv_cls/biases/Adam, ssd_300_vgg/block8_box/conv_cls/biases/Adam_1, ssd_300_vgg/block9_box/conv_loc/weights/Adam, ssd_300_vgg/block9_box/conv_loc/weights/Adam_1, ssd_300_vgg/block9_box/conv_loc/biases/Adam, ssd_300_vgg/block9_box/conv_loc/biases/Adam_1, ssd_300_vgg/block9_box/conv_cls/weights/Adam, ssd_300_vgg/block9_box/conv_cls/weights/Adam_1, ssd_300_vgg/block9_box/conv_cls/biases/Adam, ssd_300_vgg/block9_box/conv_cls/biases/Adam_1, ssd_300_vgg/block10_box/conv_loc/weights/Adam, ssd_300_vgg/block10_box/conv_loc/weights/Adam_1, ssd_300_vgg/block10_box/conv_loc/biases/Adam, ssd_300_vgg/block10_box/conv_loc/biases/Adam_1, ssd_300_vgg/block10_box/conv_cls/weights/Adam, ssd_300_vgg/block10_box/conv_cls/weights/Adam_1, ssd_300_vgg/block10_box/conv_cls/biases/Adam, ssd_300_vgg/block10_box/conv_cls/biases/Adam_1, ssd_300_vgg/block11_box/conv_loc/weights/Adam, ssd_300_vgg/block11_box/conv_loc/weights/Adam_1, ssd_300_vgg/block11_box/conv_loc/biases/Adam, ssd_300_vgg/block11_box/conv_loc/biases/Adam_1, ssd_300_vgg/block11_box/conv_cls/weights/Adam, ssd_300_vgg/block11_box/conv_cls/weights/Adam_1, ssd_300_vgg/block11_box/conv_cls/biases/Adam, ssd_300_vgg/block11_box/conv_cls/biases/Adam_1

Does anyone meet the same error？
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.92GiB
I use GeForce GTX 950M, is the error ralate with the memory?

**Comment by Amitayus** [comment]
I have the same problem with you. 
I add a new variable upon original model, then I try to warm up part of my new model with original checkpoint weight and part of my model using `tf.global_variables_initializer()`. Then the errors occur.

**Comment by Amitayus** [comment]
Step 2 in my answer on this [issue ](https://github.com/tensorflow/tensorflow/issues/13342) may help you.

**Comment by wjx2** [comment]
@ziyeshanwai @Amitayus 
hi, I have the same problem with you.
Have you solve the problem? can you help me?

**Comment by wjx2** [comment]
@ziyeshanwai @Amitayus 
Hi, I have the same problem with you.
Are you solve the problem? Can you help me?

**Comment by wjx2** [comment]
@ziyeshanwai 
Hi, I have the same problem with you.
Are you solve the problem? Can you help me?

**Comment by wjx2** [comment]
@Amitayus 
Hi, I try your solution, but a new error occur:
FailedPreconditionError: Attempting to use uninitialized value input_producer/limit_epochs/epochs
	 [[Node: input_producer/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input_producer/limit_epochs/epochs"], limit=50, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/limit_epochs/epochs)]]
Can you help me?

**Comment by wjx2** [comment]
@ziyeshanwai 
Hi, I have the same problem with you.
Are you solve the problem? Could you help me?

**Comment by wjx2** [comment]
@Amitayus 
Hi, I try your solution, but a new error occur:
FailedPreconditionError: Attempting to use uninitialized value input_producer/limit_epochs/epochs
[[Node: input_producer/limit_epochs/CountUpTo = CountUpToT=DT_INT64, _class=["loc:@input_producer/limit_epochs/epochs"], limit=50, _device="/job:localhost/replica:0/task:0/cpu:0"]]
Could you help me?

**Comment by u10116032** [comment]
@wjx2  I think maybe you can try to initialize these variables in ready_init_op, which can be set as a parameter in slim.learning.train
