### ISSUE TITLE
Got the error, how to fix it?

### ISSUE THREAD

**Issue by ivyteng** [balancap/SSD-Tensorflow#143]
lable on your machine and could speed up CPU computations.
2017-10-10 14:45:20.903417: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-10 14:45:20.903416: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-10 14:45:20.903424: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-10 14:45:20.903417: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-10 14:45:20.903451: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-10 14:45:20.903450: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-10 14:45:20.957577: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:20.957578: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:20.957688: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:20.957732: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:20.957659: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:20.957590: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:21.000302: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:21.000345: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:21.000383: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:21.000312: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:21.000322: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-10 14:45:21.000366: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "train_ssd_network.py", line 376, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 372, in main
    sync_optimizer=None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 767, in train
    sv.stop(threads, close_summary_writer=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.
	 [[Node: bboxes_encode_block_0/while/strided_slice_2 = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_encode_block_0/while/strided_slice_2/Enter, bboxes_encode_block_0/while/strided_slice_2/stack, bboxes_encode_block_0/while/strided_slice_2/stack_1, bboxes_encode_block_0/while/strided_slice_2/stack_2)]]

Do you how what the problem with the code? Thanks

**Comment by LJXLJXLJX** [comment]
I have encountered the same problem, have you solved it now?

**Comment by ypoet** [comment]
@LJXLJXLJX Have you tried HiKapok's version and succeed? if not, what's your solution to train your own dataset?
