### ISSUE TITLE
Invalid argument: slice index 0 of dimension 0 out of bounds

### ISSUE THREAD

**Issue by ivyteng** [balancap/SSD-Tensorflow#146]
When I train the model, got the following error:

2017-10-11 15:01:19.283696: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-11 15:01:19.283696: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-11 15:01:19.283696: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-11 15:01:19.283711: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-11 15:01:19.283696: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-11 15:01:19.283704: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
2017-10-11 15:01:19.460944: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 2 of dimension 0 out of bounds.
2017-10-11 15:01:19.460944: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-11 15:01:19.460991: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 2 of dimension 0 out of bounds.
2017-10-11 15:01:19.460946: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 3 of dimension 0 out of bounds.
2017-10-11 15:01:19.460955: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 2 of dimension 0 out of bounds.
2017-10-11 15:01:19.460960: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 3 of dimension 0 out of bounds.
2017-10-11 15:01:19.460968: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-11 15:01:19.460984: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 3 of dimension 0 out of bounds.
2017-10-11 15:01:19.461105: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 3 of dimension 0 out of bounds.
2017-10-11 15:01:19.461018: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-11 15:01:19.461025: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 2 of dimension 0 out of bounds.
2017-10-11 15:01:19.461027: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 3 of dimension 0 out of bounds.
2017-10-11 15:01:19.461061: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 2 of dimension 0 out of bounds.
2017-10-11 15:01:19.461046: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-11 15:01:19.461063: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 3 of dimension 0 out of bounds.
2017-10-11 15:01:19.461078: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
2017-10-11 15:01:19.461090: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 2 of dimension 0 out of bounds.
2017-10-11 15:01:19.460945: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 1 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "train_ssd_network.py", line 380, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 376, in main
    sync_optimizer=None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 767, in train
    sv.stop(threads, close_summary_writer=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.
	 [[Node: bboxes_encode_block_2/while/strided_slice_2 = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_encode_block_2/while/strided_slice_2/Enter, bboxes_encode_block_2/while/strided_slice_2/stack, bboxes_encode_block_2/while/strided_slice_2/stack_1, bboxes_encode_block_2/while/strided_slice_2/stack_2)]]

Who know what's the problem and how to fix?

Thanks

**Comment by NetWilliam** [comment]
https://github.com/tensorflow/tensorflow/issues/15568#issuecomment-353807443
