### ISSUE TITLE
Fine-tuning a network trained on ImageNet

### ISSUE THREAD

**Issue by chenweiqian** [balancap/SSD-Tensorflow#15]
Hi, thanks for your work to implement SSD on TensorFlow。It’s very helpful for me！
But now I met some mistakes。when I use my own dataset to try this step， I got error as below：

I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, Tensor name "ssd_300_vgg/block10/conv1x1/weights" not found in checkpoint files ./checkpoints/vgg_16.ckpt
	 [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_1', defined at:
  File "train_ssd_network.py", line 363, in <module>
    tf.app.run()
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 351, in main
    init_fn=tf_utils.get_init_fn(FLAGS),
  File "/home/wahaha/documents/haha/SSD-Tensorflow-master/tf_utils.py", line 225, in get_init_fn
    ignore_missing_vars=flags.ignore_missing_vars)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 584, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "ssd_300_vgg/block10/conv1x1/weights" not found in checkpoint files ./checkpoints/vgg_16.ckpt
	 [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]

Traceback (most recent call last):
  File "train_ssd_network.py", line 363, in <module>
    tf.app.run()
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 359, in main
    session_config=config)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 776, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 973, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 801, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 962, in managed_session
    start_standard_services=start_standard_services)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 719, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 264, in prepare_session
    init_fn(sess)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 586, in callback
    saver.restore(session, model_path)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "ssd_300_vgg/block10/conv1x1/weights" not found in checkpoint files ./checkpoints/vgg_16.ckpt
	 [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_1', defined at:
  File "train_ssd_network.py", line 363, in <module>
    tf.app.run()
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 351, in main
    init_fn=tf_utils.get_init_fn(FLAGS),
  File "/home/wahaha/documents/haha/SSD-Tensorflow-master/tf_utils.py", line 225, in get_init_fn
    ignore_missing_vars=flags.ignore_missing_vars)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 584, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/wahaha/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "ssd_300_vgg/block10/conv1x1/weights" not found in checkpoint files ./checkpoints/vgg_16.ckpt
	 [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]

I don‘t know why。If you know，can you tell me。Thanks ！！

**Comment by 0rland0** [comment]
I think you just have to unzip ssd_300_vgg.ckpt.zip which is located in the checkpoint folder

**Comment by chenweiqian** [comment]
@0rland0 yes,I did that.

**Comment by 0rland0** [comment]
@chenweiqian Can you maybe post the output of 
```
ls ./checkpoints/
```

**Comment by chenweiqian** [comment]
yes, I see ssd_300_vgg.ckpt.index in it. And I also tried to change vgg_16.ckpt to ssd_300_vgg.ckpt and keep rest commands frozen, it can run successfully. But when I delete the "checkpoint_exclude_scopes " command , it gets error. So my successful case is the combining of "Fine-tuning existing SSD checkpoints" and "Fine-tuning a network trained on ImageNet". Is this a success?

**Comment by chenweiqian** [comment]
@0rland0  yes, I see ssd_300_vgg.ckpt.index in it. And I also tried to change vgg_16.ckpt to ssd_300_vgg.ckpt and keep rest commands frozen, it can run successfully. But when I delete the "checkpoint_exclude_scopes " command , it gets error. So my successful case is the combining of "Fine-tuning existing SSD checkpoints" and "Fine-tuning a network trained on ImageNet". Is this a success?

**Comment by balancap** [comment]
Sorry for the problems, the script is buggy after some changes I have made :/ 
I'll fix this as soon as possible.

**Comment by chenweiqian** [comment]
@balancap thank you！^_^

**Comment by yyjFish** [comment]
I have met the same problem

**Comment by balancap** [comment]
I finally found some time to fix the bug. It should work well now!
I added to the training script a parameter checkpoint_model_scope where you can specify the main scope of the checkpoint file.
I also fixed the list of ignored scope for VGG16. It's a bit long! I could change the variable scopes in the net definition to make that simpler, but I don't want to introduce any modification not backward compatible with existing checkpoints of SSD-VGG.

**Comment by chenweiqian** [comment]
@balancap thank you for your work!
