### ISSUE TITLE
Is the CPU-training by default, or GPU training? How to modify code to enable GPU training instead of CPU training?

### ISSUE THREAD

**Issue by ivyteng** [balancap/SSD-Tensorflow#155]

**Comment by 3born** [comment]
GPU training is enabled by default at https://github.com/balancap/SSD-Tensorflow/blob/master/train_ssd_network.py#L366 if your environment is correctly configured. The GPU fraction used is set to 0.8 by default at https://github.com/balancap/SSD-Tensorflow/blob/master/train_ssd_network.py#L66, you can change this by passing some value to the `gpu_memory_fraction` flag.

You can easily check if you're using your GPU by monitoring GPU and CPU statistics. If you don't see your GPU memory being used up I'd look into the TF installation and do a quick test to see that it properly allocates memory on the GPU.

**Comment by ivyteng** [comment]
I used the default parameters(learning rate = 0.0001, batch_size = 32). But the loss doesn't converge. At iteration 30000, the loss oscillate  from 20 to 60, do you know how to fix?

**Comment by ivyteng** [comment]
I used the default parameters(learning rate = 0.0001, batch_size = 32). But the loss doesn't converge. At iteration 30000, the loss oscillate from 20 to 60, do you know how to fix?

**Comment by 3born** [comment]
Given the information you have provided there could be a million reasons for this. There are several people that have observed a loss of the same order of magnitude, e.g. https://github.com/balancap/SSD-Tensorflow/issues/67 but the explosion implies that something went terribly wrong. Did you try evaluating a model checkpoint to see if your results are any good?

**Comment by ivyteng** [comment]
@3born ,yes I test the checkpoint with the training set, MAP is slightly above 0.1, very low.

**Comment by 3born** [comment]
Alright, I assume you used a checkpoint before the loss exploded? If not, you're going to need to provide more information otherwise I can't help you.

**Comment by ivyteng** [comment]
I use the vgg_16.ckpt to initialize the weight parameters, and the loss always up and down 40. I made no changes to the program expect using NHWC, does this affect the performance? It also got wrong when I try NCHW.

**Comment by ivyteng** [comment]
@balancap 
I use the vgg_16.ckpt to initialize the weight parameters, and the loss always up and down 40. I made no changes to the program expect using NHWC, does this affect the performance? It also got wrong when I try NCHW.

**Comment by ivyteng** [comment]
@3born 
When I set the format to be "NHWC", It got the error message 

InvalidArgumentError (see above for traceback): CPU BiasOp only supports NHWC.
	 [[Node: ssd_300_vgg/conv1/conv1_1/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](ssd_300_vgg/conv1/conv1_1/convolution, ssd_300_vgg/conv1/conv1_1/biases/read)]]

I seems the program run via CPU. But I don't make any changes to the program, it should run via GPU, do you know why?

**Comment by ivyteng** [comment]
@3born Have you tested the file  tf_convert_data.py? I am wondering if there is something wrong  with the training data, resulting in large loss?

**Comment by 3born** [comment]
Yes, I've run it successfully with both VOC and my own data. You can e.g. look at input images using tensorboard if you're uncertain about the conversion.

Try running `sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))` in python. If you don't see your GPU when you type the following you will need to do something about your tensorflow.
```
...
2017-11-01 07:02:23.086480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:1e.0
Total memory: 11.17GiB
Free memory: 11.10GiB
```

**Comment by ivyteng** [comment]
@3born  This is what I got. It seems there is something wrong with my tensorflow.
Device mapping: no known devices.
2017-11-01 17:09:57.950583: I tensorflow/core/common_runtime/direct_session.cc:300] Device mapping:

**Comment by 3born** [comment]
Yeah I'd say so, try [this](https://www.tensorflow.org/install/). Be sure to config the GPU settings correctly.

After installing, run the previous command again to make sure everything's set up. After that, make sure to monitor GPU and CPU performance when starting tests. You can do this with e.g. task monitor, [GPU-Z](https://www.techpowerup.com/gpuz/), `nvidia-smi`. If you don't see a spike in GPU memory when you start your script, something is wrong.

Good luck!

**Comment by ivyteng** [comment]
@3born  Thanks to your suggestion, I can run the program via GPU.  I change the format to NCHW, but the loss is still up and down 40. I use the default parameters. Could you give me some advice, or would you like to share your pascalvoc tfrecords data with me  to test the program?

**Comment by 3born** [comment]
I ran the code as is, don't think I can add anything that isn't explained in the readme. I haven't trained from scratch, only fine-tuning. If we look at [#67](https://github.com/balancap/SSD-Tensorflow/issues/67) we see that a loss in these orders of magnitude are common for this implementation. The only suggestion is a slightly lower learning rate. 

Loss isn't everything - did you try evaluating? I did some quick tests by fine-tuning ssd_300_vgg for 100 epochs with 3 tfrecord files and evaluated on 2 different tfrecords files for a mAP of **0.7937**.  My loss bounced from 20 to 40 continuously.

Regarding tfrecords, just look in Tensorboard if your images are correct.

**Comment by ivyteng** [comment]
@3born thanks for your reply. I recently installed tensorflow-gpu (tensorflow 1.4.0). When I run the eval_ssd_network.py to evaluate my model, I got the following error

Traceback (most recent call last):
  File "eval_ssd_network.py", line 333, in <module>
    tf.app.run()
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 305, in main
    eval_op=names_to_updates.values())#,
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/evaluation.py", line 207, in evaluate_once
    config=session_config)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 182, in _evaluate_once
    eval_step_value = _get_latest_eval_step_value(eval_ops)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 75, in _get_latest_eval_step_value
    with ops.control_dependencies(update_ops):
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4304, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4017, in control_dependencies
    c = self.as_graph_element(c)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3035, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3124, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a tuple into a Tensor or Operation.

It seems there is something wrong with the following function:

slim.evaluation.evaluate_once(
                master=FLAGS.master,
                checkpoint_path=checkpoint_path,
                logdir=FLAGS.eval_dir,
                num_evals=num_batches,
                eval_op=list(names_to_updates.values()),
                variables_to_restore=variables_to_restore,
                session_config=config)

De you know how to fix the problem?

Thanks

**Comment by ivyteng** [comment]
@3born  thanks for your reply. I recently installed tensorflow-gpu (tensorflow 1.4.0). When I run the eval_ssd_network.py to evaluate my model, I got the following error

INFO:tensorflow:Evaluating /home/ai-i-wangteng/Teng/SSD-TensorFlowNew/train_dir/model.ckpt-539145
Traceback (most recent call last):
  File "eval_ssd_network.py", line 333, in <module>
    tf.app.run()
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 307, in main
    session_config=config)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/evaluation.py", line 207, in evaluate_once
    config=session_config)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 182, in _evaluate_once
    eval_step_value = _get_latest_eval_step_value(eval_ops)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 75, in _get_latest_eval_step_value
    with ops.control_dependencies(update_ops):
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4304, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4017, in control_dependencies
    c = self.as_graph_element(c)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3035, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3124, in _as_graph_element_locked
    types_str))
**TypeError: Can not convert a tuple into a Tensor or Operation.**

**It seems there is something wrong with the following function:**

slim.evaluation.evaluate_once(
master=FLAGS.master,
checkpoint_path=checkpoint_path,
logdir=FLAGS.eval_dir,
num_evals=num_batches,
eval_op=list(names_to_updates.values()),
variables_to_restore=variables_to_restore,
session_config=config)

De you know how to fix the problem?

Thanks

**Comment by ivyteng** [comment]
@3born  @balancap Thanks for you reply. I try to run eval_ssd_network to evaluate mu model, I got the following error:

INFO:tensorflow:Evaluating /home/ai-i-wangteng/Teng/SSD-TensorFlowNew/train_dir/model.ckpt-539145
Traceback (most recent call last):
  File "eval_ssd_network.py", line 333, in <module>
    tf.app.run()
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 307, in main
    session_config=config)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/evaluation.py", line 207, in evaluate_once
    config=session_config)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 182, in _evaluate_once
    eval_step_value = _get_latest_eval_step_value(eval_ops)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 75, in _get_latest_eval_step_value
    with ops.control_dependencies(update_ops):
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4304, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4017, in control_dependencies
    c = self.as_graph_element(c)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3035, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/ai-i-wangteng/Teng/tool/wtf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3124, in _as_graph_element_locked
    types_str))
**TypeError: Can not convert a tuple into a Tensor or Operation.**

**It seems there is something wrong with calling the function:**

slim.evaluation.evaluate_once(
                master=FLAGS.master,
                checkpoint_path=checkpoint_path,
                logdir=FLAGS.eval_dir,
                num_evals=num_batches,
                eval_op=list(names_to_updates.values()),
                variables_to_restore=variables_to_restore,
                session_config=config)

DO you know how to fix it?

**Comment by ivyteng** [comment]
@3born , I train the model more than 50+w, the loss  is up and down 30. I evaluate the model with the following metric:

2017-11-06 18:49:45.809803: I tensorflow/core/kernels/logging_ops.cc:79] AP_VOC07/mAP[0.36998718900122729]
2017-11-06 18:51:05.969679: I tensorflow/core/kernels/logging_ops.cc:79] AP_VOC12/mAP[0.35381859220573314]

the results are not as good as expected.

**Comment by Janezzliu** [comment]
@ivyteng I train the code on my own data and evaluate it. My evaluation's mAP is the same as you.Have you improved the mAP later?And could you please tell me the solution?Thanks a lot!

**Comment by huangx06** [comment]
I also got the same poor results, but do not know why
