### ISSUE TITLE
NotFoundError: Failed to create a NewWriteableFile

### ISSUE THREAD

**Issue by JinwenJay** [balancap/SSD-Tensorflow#187]
### I tried to convert the VOC2007 datasets to TF-Records using the tf_convert_data.py like this:

python tf_convert_data.py --dataset_name=pascalvoc --dataset_dir=VOCdevkit/VOC2007/test/ --output_name=voc_2007_test --output_dir=VOCdevkit/tfrecords

### And I had download the VOC2007 datasets in the corresponding path. Following is the problem I am confused with.

Dataset directory: VOCdevkit/VOC2007/test/
Output directory: VOCdevkit/tfrecords
Traceback (most recent call last):
  File "tf_convert_data.py", line 59, in <module>
    tf.app.run()
  File "C:\Users\Jinwen Tan\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tf_convert_data.py", line 54, in main
    pascalvoc_to_tfrecords.run(FLAGS.dataset_dir, FLAGS.output_dir, FLAGS.output_name)
  File "C:\Users\Jinwen Tan\Documents\SSD-tensorflow\SSD-Tensorflow-master\datasets\pascalvoc_to_tfrecords.py", line 210, in run
    with tf.python_io.TFRecordWriter(tf_filename) as tfrecord_writer:
  File "C:\Users\Jinwen Tan\Anaconda3\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "C:\Users\Jinwen Tan\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: VOCdevkit/tfrecords/voc_2007_test_000.tfrecord : \u03f5\u0373\udcd5\u04b2\udcbb\udcb5\udcbd\u05b8\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

### Besides, I run this code in windows cmd, does it matter? I mean whether this problem will disappear if I use ubuntu?

**Comment by JinwenJay** [comment]
I know the recommended form in https://github.com/balancap/SSD-Tensorflow like this:DATASET_DIR=./VOC2007/test/
OUTPUT_DIR=./tfrecords
python tf_convert_data.py \
    --dataset_name=pascalvoc \
    --dataset_dir=${DATASET_DIR} \
    --output_name=voc_2007_train \
    --output_dir=${OUTPUT_DIR}
But I use windows, it seems I can't run the script in this way.

**Comment by dmy1997** [comment]
hey! Have you solve it? I have the same question as you.

**Comment by liruixl** [comment]
You need to creat a dir by yourself, like VOCdevkit/tfrecords, at your running  environment folder where you run this script. @dmy1997

**Comment by murraykkkeed06** [comment]
have the same question have you solved it?

**Comment by murraykkkeed06** [comment]
> You need to creat a dir by yourself, like VOCdevkit/tfrecords, at your running environment folder where you run this script. @dmy1997

i did add the folder, but has the same error again
