### ISSUE TITLE
var_list cannot be empty

### ISSUE THREAD

**Issue by Tanakasu** [balancap/SSD-Tensorflow#260]
I want to try fine-tuning with my own dataset by ssd_512.
this is my input

----------------------------------------------------------------------------------------------------------
DATASET_DIR=./tfrecords/
TRAIN_DIR=./log/
CHECKPOINT_PATH=./checkpoints/VGG_VOC0712_SSD_512x512_ft_iter_120000.ckpt/VGG_VOC0712_SSD_512x512_ft_iter_120000.ckpt/
python train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2012 \
    --dataset_split_name=train \
    --num_classes=8 \
    --model_name=ssd_512_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --checkpoint_model_scope=ssd_512_vgg \
    --checkpoint_exclude_scopes=ssd_512_vgg/block10,ssd_512_vgg/block10_box,ssd_512_vgg/block11,ssd_512_vgg/block11_box,ssd_512_vgg/block12,ssd_512_vgg/block12_box,ssd_512_vgg/block4_box,ssd_512_vgg/block7_box,ssd_512_vgg/block8,ssd_512_vgg/block8_box,ssd_512_vgg/block9,ssd_512_vgg/block9_box,ssd_512_vgg/conv6,ssd_512_vgg/conv7,ssd_512_vgg \
    --trainable_scopes=ssd_512_vgg/block10,ssd_512_vgg/block10_box,ssd_512_vgg/block11,ssd_512_vgg/block11_box,ssd_512_vgg/block12,ssd_512_vgg/block12_box,ssd_512_vgg/block4_box,ssd_512_vgg/block7_box,ssd_512_vgg/block8,ssd_512_vgg/block8_box,ssd_512_vgg/block9,ssd_512_vgg/block9_box,ssd_512_vgg/conv6,ssd_512_vgg/conv7,ssd_512_vgg \
    --save_summaries_secs=600 \
    --save_interval_secs=600 \
    --weight_decay=0.0005 \
    --optimizer=adam \
    --learning_rate=0.001 \
    --learning_rate_decay_factor=0.94 \
    --batch_size=32
----------------------------------------------------------------------------------------------------------

but, I got a problem like below.
----------------------------------------------------------------------------------------------------------
INFO:tensorflow:Fine-tuning from ./checkpoints/VGG/VGG_VOC0712_SSD_512x512_ft_iter_120000.ckpt/. Ignoring missing vars: False
Traceback (most recent call last):
  File "train_ssd_network.py", line 391, in <module>
    tf.app.run()
  File "/home/dl-box/anaconda3/envs/tensorflow14/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_ssd_network.py", line 378, in main
    init_fn=tf_utils.get_init_fn(FLAGS),
  File "/home/dl-box/SSD-Tensorflow-master/tf_utils.py", line 235, in get_init_fn
    ignore_missing_vars=flags.ignore_missing_vars)
  File "/home/dl-box/anaconda3/envs/tensorflow14/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 672, in assign_from_checkpoint_fn
    raise ValueError('var_list cannot be empty')
ValueError: var_list cannot be empty
----------------------------------------------------------------------------------------------------------

It seems  variables_to_restore ( in the function [get_init_fn in tf_utils.py]) is empty.
How can I solve this?

**Comment by zhouqzzw** [comment]
I got the same problem...
