### ISSUE TITLE
invalid syntax error in tf_util.py

### ISSUE THREAD

**Issue by gaopeng-eugene** [balancap/SSD-Tensorflow#28]
Traceback (most recent call last):
  File "train_ssd_network.py", line 23, in <module>
    import tf_utils
  File "/opt/data/penggao/deep_detection/SSD-Tensorflow/tf_utils.py", line 65
    print('\n# =========================================================================== #', file=stream)
                                                                                                   ^
SyntaxError: invalid syntax

**Comment by miraclebiu** [comment]
from __future__ import print_function

**Comment by balancap** [comment]
@miraclebiu Thanks! I'll try to make the project Python 2 compatible to avoid this kind of bugs.

**Comment by youngwanLEE** [comment]
from __future__ import print_function

**Comment by cooliscool** [comment]
This helped. 
https://stackoverflow.com/questions/32032697/how-to-use-from-future-import-print-function

Dear python 2 users, you have to add 
`from __future__ import print_function`
as your first line in code.
