### ISSUE TITLE
ResourceExhaustedError  (see above for traceback): OOM when allocating tensor with shape[279424,4]

### ISSUE THREAD

**Issue by lzh19961031** [balancap/SSD-Tensorflow#283]
[[Node: ssd_losses/localization/sub_1 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd_losses/localization/Abs, ssd_losses/localization/sub_1/y)]]

Caused by op u'ssd_losses/localization/sub_1', defined at:
  File "train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 291, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/home/liuzihao/SSD-Tensorflow/deployment/model_deploy.py", line 196, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "train_ssd_network.py", line 282, in clone_fn
    label_smoothing=FLAGS.label_smoothing)
  File "/home/liuzihao/SSD-Tensorflow/nets/ssd_vgg_300.py", line 248, in losses
    scope=scope)
  File "/home/liuzihao/SSD-Tensorflow/nets/ssd_vgg_300.py", line 654, in ssd_losses
    loss = custom_layers.abs_smooth(localisations - glocalisations)
  File "/home/liuzihao/SSD-Tensorflow/nets/custom_layers.py", line 42, in abs_smooth
    r = 0.5 * ((absx - 1) * minx + absx)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4636, in _sub
    "Sub", x=x, y=y, name=name)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[279424,4]
	 [[Node: ssd_losses/localization/sub_1 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd_losses/localization/Abs, ssd_losses/localization/sub_1/y)]]

Traceback (most recent call last):
  File "train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 386, in main
    sync_optimizer=None)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 763, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 487, in train_step
    run_metadata=run_metadata)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[279424,4]
	 [[Node: ssd_losses/localization/sub_1 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd_losses/localization/Abs, ssd_losses/localization/sub_1/y)]]

Caused by op u'ssd_losses/localization/sub_1', defined at:
  File "train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 291, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/home/liuzihao/SSD-Tensorflow/deployment/model_deploy.py", line 196, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "train_ssd_network.py", line 282, in clone_fn
    label_smoothing=FLAGS.label_smoothing)
  File "/home/liuzihao/SSD-Tensorflow/nets/ssd_vgg_300.py", line 248, in losses
    scope=scope)
  File "/home/liuzihao/SSD-Tensorflow/nets/ssd_vgg_300.py", line 654, in ssd_losses
    loss = custom_layers.abs_smooth(localisations - glocalisations)
  File "/home/liuzihao/SSD-Tensorflow/nets/custom_layers.py", line 42, in abs_smooth
    r = 0.5 * ((absx - 1) * minx + absx)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4636, in _sub
    "Sub", x=x, y=y, name=name)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/liuzihao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[279424,4]
	 [[Node: ssd_losses/localization/sub_1 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd_losses/localization/Abs, ssd_losses/localization/sub_1/y)]]

 Above those it says that  cuda out of memory, is it the problem of that?

**Comment by KKKlose** [comment]
maybe your GPU memory is not enough ,you can try lower the batch_size
