### ISSUE TITLE
ValueError: No variables to optimize.

### ISSUE THREAD

**Issue by engineer1109** [balancap/SSD-Tensorflow#311]
Traceback (most recent call last):
  File "train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_ssd_network.py", line 345, in main
    var_list=variables_to_train)
  File "/media/wjl/back/SSD-Tensorflow/deployment/model_deploy.py", line 301, in optimize_clones
    optimizer, clone, num_clones, regularization_losses, **kwargs)
  File "/media/wjl/back/SSD-Tensorflow/deployment/model_deploy.py", line 265, in _optimize_clone
    clone_grad = optimizer.compute_gradients(sum_loss, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 520, in compute_gradients
    raise ValueError("No variables to optimize.")
ValueError: No variables to optimize.

Training from VGG error.

**Comment by engineer1109** [comment]
It is my fault. I forget to replace all 300 to 512.
