### ISSUE TITLE
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints

### ISSUE THREAD

**Issue by AndreaFar** [balancap/SSD-Tensorflow#34]
After that I have followed all the instructions of readme

running the following command:
```
EVAL_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
python eval_ssd_network.py \
    --eval_dir=${EVAL_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=test \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --batch_size=1
```

I get the error **_Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints_**
```

Here what I see on the console output:
# =========================================================================== #
# Training | Evaluation dataset files:
# =========================================================================== #
['VOC2007/test/voc_2007_test.tfrecord']

INFO:tensorflow:Evaluating checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\training\python\training\evaluation.py:298: SummaryWriter.__init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
INFO:tensorflow:Starting evaluation at 2017-03-21-16:28:30
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt

         [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_ssd_network.py", line 346, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 320, in main
    session_config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\evaluation.py", line 207, in evaluate_once
    config=session_config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\training\python\training\evaluation.py", line 427, in evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 601, in __init__
    session_creator, hooks, should_recover=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 434, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 767, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 772, in _create_session
    return self._sess_creator.create_session()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 494, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 375, in create_session
    init_fn=self._scaffold.init_fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\session_manager.py", line 256, in prepare_session
    config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\session_manager.py", line 172, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt

         [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]

Caused by op 'save/RestoreV2_18', defined at:
  File "eval_ssd_network.py", line 346, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 320, in main
    session_config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\evaluation.py", line 195, in evaluate_once
    saver = tf_saver.Saver(variables_to_restore)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1040, in __init__
    self.build()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 675, in build
    restore_sequentially, reshape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
    self._traceback = _extract_stack()
```

I'm using Tensorflow 1.0.1

**Comment by mysope** [comment]
Could I ask a simple question?
How did you make 'voc_2007_test.tfrecord' file? 
I can't find the process for making this test file in README.

**Comment by swetshaw** [comment]
After extracting the zip file in checkpoints folder . I didn't get "VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt" file.

**Comment by MagnIeeT** [comment]
Use absolute path instead of relative path. It worked for me.

**Comment by damononliu** [comment]
> After extracting the zip file in checkpoints folder . I didn't get "VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt" file.

have you solved it?
