### ISSUE TITLE
RuntimeError: generator didn't yield

### ISSUE THREAD

**Issue by amilyxy** [balancap/SSD-Tensorflow#342]
Hello， I'm running the SSD repo，but it‘s something wrong with the output:
“
**INFO:tensorflow:Restoring parameters from ./checkpoints/ssd_300_vgg.ckpt
2019-04-23 11:40:16.227131: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "train_ssd_network.py", line 391, in <module>
    tf.app.run()
  File "/home/amilyxy/miniconda3/envs/py36_tf18/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_ssd_network.py", line 387, in main
    sync_optimizer=None)
  File "/home/amilyxy/miniconda3/envs/py36_tf18/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 747, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/home/amilyxy/miniconda3/envs/py36_tf18/lib/python3.6/contextlib.py", line 83, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield**
”
my environment is tensorflow-gpu=1.8.0 and Titan X
I have been confused many days！！！I Does anyone else meet the same problem too?

**Comment by GoodMan0** [comment]
I met the same problem with you. Did you solve the problem?
