### ISSUE TITLE
Train your own dataset to report an error, run train_ssd_network to report an error

### ISSUE THREAD

**Issue by liu978079474** [balancap/SSD-Tensorflow#376]
Hello, when I run training ssd network, something went wrong, here is the full log：
D:\python3.6\python.exe D:/Project/MyLearning/SSD-Tensorflow-master/train_ssd_network.py

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From D:/Project/MyLearning/SSD-Tensorflow-master/train_ssd_network.py:200: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:From D:\python3.6\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "D:/Project/MyLearning/SSD-Tensorflow-master/train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "D:\python3.6\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:/Project/MyLearning/SSD-Tensorflow-master/train_ssd_network.py", line 204, in main
    FLAGS.dataset_name, FLAGS.dataset_split_name, FLAGS.dataset_dir)
  File "D:\Project\MyLearning\SSD-Tensorflow-master\datasets\dataset_factory.py", line 55, in get_dataset
    reader)
  File "D:\Project\MyLearning\SSD-Tensorflow-master\datasets\imagenet.py", line 183, in get_split
    labels_to_names = create_readable_names_for_imagenet_labels()
  File "D:\Project\MyLearning\SSD-Tensorflow-master\datasets\imagenet.py", line 90, in create_readable_names_for_imagenet_labels
    filename, _ = urllib.request.urlretrieve(synset_url)
  File "D:\python3.6\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\python3.6\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\python3.6\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "D:\python3.6\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\python3.6\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "D:\python3.6\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\python3.6\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Process finished with exit code 1

Thank you！

**Comment by chengyangkj** [comment]
I got the same problem,it's HTTP error ,train is need to download from the network?

**Comment by Kervin-L** [comment]
Hello, you need to download network model vgg16, if you want to train from scratch, then you need to modify the configuration parameters of the training run.
