### ISSUE TITLE
AttributeError: 'module' object has no attribute 'losses'

### ISSUE THREAD

**Issue by busrakb** [balancap/SSD-Tensorflow#47]
Hi,
the working code;
EVAL_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt
python eval_ssd_network.py \
    --eval_dir=${EVAL_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=test \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --batch_size=1

When it is worked , it give the error that is;
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
['/home/eud/busra_face/SSD-Tensorflow-master/tfrecords/voc_2007_test.tfrecord']
Traceback (most recent call last):
  File "eval_ssd_network.py", line 346, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 190, in main
    b_gclasses, b_glocalisations, b_gscores)
  File "/home/eud/busra_face/SSD-Tensorflow-master/nets/ssd_vgg_300.py", line 248, in losses
    scope=scope)
  File "/home/eud/busra_face/SSD-Tensorflow-master/nets/ssd_vgg_300.py", line 639, in ssd_losses
    loss = tf.losses.compute_weighted_loss(loss, fpmask)
AttributeError: 'module' object has no attribute 'losses'

i couldn't find any solution. Can you help me?

**Comment by taras-sereda** [comment]
Looks like you use old tensorflow version. your tf installation version should be >= 1.0
```python -c "import tenosrflow; print tensorflow.__version__"```

**Comment by busrakb** [comment]
when i look at your code, i saw the tf 0.12.1. but when i install tf (pip
install 'tensorflow>=1.0') it gives

Requirement already satisfied: tensorflow>=1.0 in
/usr/local/lib/python2.7/dist-packages
Requirement already satisfied: mock>=2.0.0 in
/usr/local/lib/python2.7/dist-packages (from tensorflow>=1.0)
Requirement already satisfied: numpy>=1.11.0 in
/usr/local/lib/python2.7/dist-packages (from tensorflow>=1.0)
Requirement already satisfied: protobuf>=3.1.0 in
/usr/local/lib/python2.7/dist-packages (from tensorflow>=1.0)
Requirement already satisfied: wheel in /usr/lib/python2.7/dist-packages
(from tensorflow>=1.0)
Requirement already satisfied: six>=1.10.0 in
/usr/lib/python2.7/dist-packages (from tensorflow>=1.0)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in
/usr/local/lib/python2.7/dist-packages (from mock>=2.0.0->tensorflow>=1.0)
Requirement already satisfied: pbr>=0.11 in
/usr/local/lib/python2.7/dist-packages (from mock>=2.0.0->tensorflow>=1.0)
Requirement already satisfied: setuptools in
/usr/local/lib/python2.7/dist-packages (from
protobuf>=3.1.0->tensorflow>=1.0)
Requirement already satisfied: appdirs>=1.4.0 in
/usr/local/lib/python2.7/dist-packages (from
setuptools->protobuf>=3.1.0->tensorflow>=1.0)
Requirement already satisfied: packaging>=16.8 in
/usr/local/lib/python2.7/dist-packages (from
setuptools->protobuf>=3.1.0->tensorflow>=1.0)
Requirement already satisfied: pyparsing in
/usr/local/lib/python2.7/dist-packages (from
packaging>=16.8->setuptools->protobuf>=3.1.0->tensorflow>=1.0)

Then again i look at tf version, it still same 0.12.1

what do i need to do ? i need to install tensorflow again from source?


2017-03-31 14:13 GMT+03:00 Taras Sereda <notifications@github.com>:

**Comment by monjoybme** [comment]
**This is just an update as the issue is still open.**  

If you are using an old version of TensorFlow<1.10, you might face this issue. I was facing same error in Tensorflow Version 0.12.1 but in Tensorflow version 1.10.1 I didn't face any issue.
