### ISSUE TITLE
Reduction axis 0 is empty in shape [0]

### ISSUE THREAD

**Issue by villanuevab** [balancap/SSD-Tensorflow#66]
I'm trying to evaluate performance on Pascal VOC 2007 using the supplied VGG checkpoint weights. However, upon running the command: 
```
python eval_ssd_network.py --eval_dir=.logs/ --dataset_dir=/home/my_data/voc2007_tfrecords/ --dataset_name=pascalvoc_2007 --dataset_split_name=train --model_name=ssd_300_vgg --checkpoint_path=./checkpoints/ssd_300_vgg.ckpt --batch_size=1
```
the following error is raised (the whole stacktrace is copied below): 
```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally

# =========================================================================== #
# Training | Evaluation flags:
# =========================================================================== #
{'batch_size': 1,
 'checkpoint_path': './checkpoints/ssd_300_vgg.ckpt',
 'dataset_dir': '/home/my_data/voc2007_tfrecords/',
 'dataset_name': 'pascalvoc_2007',
 'dataset_split_name': 'train',
 'eval_dir': '.logs/',
 'eval_image_size': None,
 'eval_resize': 4,
 'gpu_memory_fraction': 0.1,
 'keep_top_k': 200,
 'master': '',
 'matching_threshold': 0.5,
 'max_num_batches': None,
 'model_name': 'ssd_300_vgg',
 'moving_average_decay': None,
 'nms_threshold': 0.45,
 'num_classes': 21,
 'num_preprocessing_threads': 4,
 'preprocessing_name': None,
 'remove_difficult': True,
 'select_threshold': 0.01,
 'select_top_k': 400,
 'wait_for_checkpoints': False}

# =========================================================================== #
# SSD net parameters:
# =========================================================================== #
{'anchor_offset': 0.5,
 'anchor_ratios': [[2, 0.5],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5],
                   [2, 0.5]],
 'anchor_size_bounds': [0.15, 0.9],
 'anchor_sizes': [(21.0, 45.0),
                  (45.0, 99.0),
                  (99.0, 153.0),
                  (153.0, 207.0),
                  (207.0, 261.0),
                  (261.0, 315.0)],
 'anchor_steps': [8, 16, 32, 64, 100, 300],
 'feat_layers': ['block4', 'block7', 'block8', 'block9', 'block10', 'block11'],
 'feat_shapes': [(38, 38), (19, 19), (10, 10), (5, 5), (3, 3), (1, 1)],
 'img_shape': (300, 300),
 'no_annotation_label': 21,
 'normalizations': [20, -1, -1, -1, -1, -1],
 'num_classes': 21,
 'prior_scaling': [0.1, 0.1, 0.2, 0.2]}

# =========================================================================== #
# Training | Evaluation dataset files:
# =========================================================================== #
['/home/my_data/voc2007_tfrecords/voc_2007_train_000.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_001.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_002.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_003.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_004.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_005.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_006.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_007.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_008.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_009.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_010.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_011.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_012.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_013.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_014.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_015.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_016.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_017.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_018.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_019.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_020.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_021.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_022.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_023.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_024.tfrecord',
 '/home/my_data/voc2007_tfrecords/voc_2007_train_025.tfrecord']

INFO:tensorflow:Evaluating ./checkpoints/ssd_300_vgg.ckpt
WARNING:tensorflow:From /home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/evaluation.py:298: __init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
INFO:tensorflow:Starting evaluation at 2017-04-19-00:44:30
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Graphics Device
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:04:00.0
Total memory: 10.91GiB
Free memory: 10.52GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Graphics Device, pci bus id: 0000:04:00.0)
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.08GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.14GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.08GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.37GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.18GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.37GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Reduction axis 0 is empty in shape [0]
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/mul, bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/ArgMax/dimension)]]
Traceback (most recent call last):
  File "eval_ssd_network.py", line 346, in <module>
    tf.app.run()
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 320, in main
    session_config=config)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/evaluation.py", line 207, in evaluate_once
    config=session_config)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/evaluation.py", line 430, in evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 891, in run
    run_metadata=run_metadata)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 0 is empty in shape [0]
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/mul, bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/ArgMax/dimension)]]
	 [[Node: ssd_losses/cross_entropy_neg/value/_548 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_7570_ssd_losses/cross_entropy_neg/value", _device="/job:localhost/replica:0/task:0/gpu:0"](ssd_losses/cross_entropy_neg/value)]]

Caused by op u'bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/ArgMax', defined at:
  File "eval_ssd_network.py", line 346, in <module>
    tf.app.run()
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_ssd_network.py", line 207, in main
    matching_threshold=FLAGS.matching_threshold)
  File "/home/experiments/SSD-Tensorflow/tf_extended/bboxes.py", line 363, in bboxes_matching_batch
    matching_threshold)
  File "/home/experiments/SSD-Tensorflow/tf_extended/bboxes.py", line 379, in bboxes_matching_batch
    infer_shape=True)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 387, in map_fn
    swap_memory=swap_memory)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2605, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2438, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2388, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 377, in compute
    packed_fn_values = fn(packed_values)
  File "/home/experiments/SSD-Tensorflow/tf_extended/bboxes.py", line 373, in <lambda>
    matching_threshold),
  File "/home/experiments/SSD-Tensorflow/tf_extended/bboxes.py", line 322, in bboxes_matching
    back_prop=False)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2605, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2438, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2388, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/experiments/SSD-Tensorflow/tf_extended/bboxes.py", line 296, in m_body
    idxmax = tf.cast(tf.argmax(jaccard, axis=0), tf.int32)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 173, in argmax
    return gen_math_ops.arg_max(input, axis, name)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 168, in arg_max
    name=name)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/miniconda2/envs/python27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Reduction axis 0 is empty in shape [0]
	 [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/mul, bboxes_matching_batch_dict/bboxes_matching_batch_17/map/while/bboxes_matching_single/while/ArgMax/dimension)]]
	 [[Node: ssd_losses/cross_entropy_neg/value/_548 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_7570_ssd_losses/cross_entropy_neg/value", _device="/job:localhost/replica:0/task:0/gpu:0"](ssd_losses/cross_entropy_neg/value)]]
```

My understanding is that this is a dimensionality issue in one of the layers of the network. Could this be caused by the input being malformed?

**Comment by villanuevab** [comment]
Closing issue. Bug was on my end in a separate pre-processing step.

**Comment by blake-varden** [comment]
I'm still getting this issue.  What was the solution?

**Comment by KosukeArase** [comment]
@villanuevab Hi. I have the same issue, can you tell me the solution?

**Comment by congjianting** [comment]
can you tell me the solution? please

**Comment by Cuky88** [comment]
@villanuevab Is it possible that you tell us how you've solved this issue, please? I'm also running into it, but I didn't change anything, except this [fix](https://github.com/balancap/SSD-Tensorflow/issues/154). Preprocessing is from ssd_300_vgg and ssd_300_vgg.ckpt. I use a custom made tfrecords (one file with 493 images), with the code from pascalvoc_2012.py copied and modified.

This is the error:
``` 
INFO:tensorflow:Restoring parameters from weights/SSDVGG/ssd_300_vgg.ckpt
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 0 is empty in shape [0]
         [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/mul, bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/bboxes_jaccard/transpose/Range/start)]]
         [[Node: streaming_tp_fp_20/AssignAdd_1/_1258 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_14614_streaming_tp_fp_20/AssignAdd_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_ssd_network.py", line 356, in <module>
    tf.app.run()
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "eval_ssd_network.py", line 330, in main
    session_config=config)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\slim\python\slim\evaluation.py", line 212, in evaluate_once
    config=session_config)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\evaluation.py", line 212, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1013, in run
    run_metadata=run_metadata)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1104, in run
    raise six.reraise(*original_exc_info)
  File "C:\Users\aklanog\AppData\Roaming\Python\Python35\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1161, in run
    run_metadata=run_metadata)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\monitored_session.py", line 941, in run
    return self._sess.run(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 0 is empty in shape [0]
         [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/mul, bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/bboxes_jaccard/transpose/Range/start)]]
         [[Node: streaming_tp_fp_20/AssignAdd_1/_1258 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_14614_streaming_tp_fp_20/AssignAdd_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/ArgMax', defined at:
  File "eval_ssd_network.py", line 356, in <module>
    tf.app.run()
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "eval_ssd_network.py", line 217, in main
    matching_threshold=FLAGS.matching_threshold)
  File "D:\Devel\CNN_Depth_Estimation\Multi2\SSD-Tensorflow\tf_extended\bboxes.py", line 363, in bboxes_matching_batch
    matching_threshold)
  File "D:\Devel\CNN_Depth_Estimation\Multi2\SSD-Tensorflow\tf_extended\bboxes.py", line 379, in bboxes_matching_batch
    infer_shape=True)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 409, in map_fn
    swap_memory=swap_memory)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 399, in compute
    packed_fn_values = fn(packed_values)
  File "D:\Devel\CNN_Depth_Estimation\Multi2\SSD-Tensorflow\tf_extended\bboxes.py", line 373, in <lambda>
    matching_threshold),
  File "D:\Devel\CNN_Depth_Estimation\Multi2\SSD-Tensorflow\tf_extended\bboxes.py", line 322, in bboxes_matching
    back_prop=False)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "D:\Devel\CNN_Depth_Estimation\Multi2\SSD-Tensorflow\tf_extended\bboxes.py", line 296, in m_body
    idxmax = tf.cast(tf.argmax(jaccard, axis=0), tf.int32)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 208, in argmax
    return gen_math_ops.arg_max(input, axis, name=name, output_type=output_type)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 508, in arg_max
    name=name)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Reduction axis 0 is empty in shape [0]
         [[Node: bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/mul, bboxes_matching_batch_dict/bboxes_matching_batch_12/map/while/bboxes_matching_single/while/bboxes_jaccard/transpose/Range/start)]]
         [[Node: streaming_tp_fp_20/AssignAdd_1/_1258 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_14614_streaming_tp_fp_20/AssignAdd_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
``` 

Starting command:
``` bash
python eval_ssd_network.py --eval_dir=logs/eval_1/ --dataset_dir=Data/GTAV/png/ --dataset_name=gtav --dataset_split_name=train --model_name=ssd_300_vgg --num_classes=21 --checkpoint_path=weights/SSDVGG/ssd_300_vgg.ckpt --batch_size=1 --remove_difficult=False --wait_for_checkpoints=False
```

**Comment by lishaofeng** [comment]
anyone has solutions?

**Comment by agrichron** [comment]
@Cuky88  the problem probaly is that there is no gbboxes, try to check the files xml.

**Comment by StephenGreat** [comment]
@Cuky88 : The answer from @Lasper2016 is right, but not clear.
In my case, I used self-made test data for evaluation and came across the same error. The reason is that the count(100) of my test data is not equal to the defined param **test** in pascalvoc_2007.py
`SPLITS_TO_SIZES = {`
`    'train': 8000,`
`    'test': 520,`
`}`
thus, there are no more gbboxes. 
So, try to change the **test** to real counts of total images in your dataset.

**Comment by dageita** [comment]
> @ Cuky88 问题可能是没有gbboxes，请尝试检查文件xml。

That's right, eval code works after I deleted the zero bounding box data.
