### ISSUE TITLE
Cannot fine-tuning existing SSD checkpoints

### ISSUE THREAD

**Issue by xujuntwt95329** [balancap/SSD-Tensorflow#79]
when I run 

```bash
DATASET_DIR=./tfrecords
TRAIN_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt
python train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2012 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.0005 \
    --optimizer=adam \
    --learning_rate=0.001 \
    --batch_size=32
```

it returns

```bash
……

INFO:tensorflow:Fine-tuning from None. Ignoring missing vars: False
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.43GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
INFO:tensorflow:Error reported to Coordinator: <class 'SystemError'>, <built-in function TF_Run> returned a result with an error set
TypeError: expected bytes, NoneType found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_ssd_network.py", line 386, in main
    sync_optimizer=None)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 776, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 973, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 801, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 962, in managed_session
    start_standard_services=start_standard_services)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 719, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 264, in prepare_session
    init_fn(sess)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 586, in callback
    saver.restore(session, model_path)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/home/xujun/anaconda3/envs/ssd2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
SystemError: <built-in function TF_Run> returned a result with an error set

```

and I don't know what is wrong, anyone encounter this problem?

**Comment by mndmchn** [comment]
The checkpoint parameter seems to expect the file not the directory.

`CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt`

solved the issue for me.

**Comment by xujuntwt95329** [comment]
@mndmchn This work for me, too
Thank you very much for solving my problem !!!

**Comment by KindleHe** [comment]
Hello，Ｉmeet the same problem as yours, but don't understand why change CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt to CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt could solve the problem.  I tried this change but failed, waiting for your help, thank you！

**Comment by xujuntwt95329** [comment]
@KindleHe 
Hello，
in 
``` bash
CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt
```
the first "ssd_300_vgg.ckpt" is the name of the folder, and the last one is the name of the checkpoint file, so this change works.
I think you should check your path to ensure that the CHECKPOINT_PATH point to the checkpoint file, you can also use absolute path to have a try.

If this doesn't work, I have to say sorry that I can't help you more, you can open a new question with your error code. 
Good luck!

**Comment by KindleHe** [comment]
I set the right path but still work wrongly with the same error. But I tried another way to finish training process successfully by change --optimizer=adam \ to --optimizer=sgd \ ，Namely, the error is caused by the parameter adam. It's hard to understand the reason why it works with the change from adam to sgd ! Any help will be appreciated!

**Comment by FiveMaster** [comment]
@KindleHe hello,I meet the same issue, and I have changed --optimizer=adam \ to --optimizer=sgd \ , but it still work wrongly. 
Should I change other parameters?
Any help will be appreciated.
The Error Info:
2017-07-13 14:44:44.628998: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:961] DMA: 0 
2017-07-13 14:44:44.629162: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   Y 
2017-07-13 14:44:44.629338: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
INFO:tensorflow:Restoring parameters from ./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /tmp/tfmodel/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, indices[0] = 0 is not in [0, 0)
	 [[Node: ssd_preprocessing_train/distorted_bounding_box_crop/bboxes_filter/boolean_mask/Gather = Gather[Tindices=DT_INT64, Tparams=DT_INT64, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ssd_preprocessing_train/distorted_bounding_box_crop/bboxes_filter/boolean_mask/Reshape, ssd_preprocessing_train/distorted_bounding_box_crop/bboxes_filter/boolean_mask/Squeeze)]]
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "D:/MachineLearning/SSD-Tensorflow/train_ssd_network.py", line 390, in <module>
    tf.app.run()
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:/MachineLearning/SSD-Tensorflow/train_ssd_network.py", line 386, in main
    sync_optimizer=None)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 759, in train
    sv.saver.save(sess, sv.save_path, global_step=sv.global_step)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "C:\Users\MasterFive\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 0 is not in [0, 0)
	 [[Node: ssd_preprocessing_train/distorted_bounding_box_crop/bboxes_filter/boolean_mask/Gather = Gather[Tindices=DT_INT64, Tparams=DT_INT64, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ssd_preprocessing_train/distorted_bounding_box_crop/bboxes_filter/boolean_mask/Reshape, ssd_preprocessing_train/distorted_bounding_box_crop/bboxes_filter/boolean_mask/Squeeze)]]

Process finished with exit code 1

**Comment by Erdos001** [comment]
@KindleHe thank you very much
I solved the problem as you said:
chang the --optimizer ADAGRAD to --optimizer ADAM

**Comment by gul98** [comment]
2017-09-03 01:35:49.055993: E tensorflow/stream_executor/cuda/cuda_dnn.cc:359] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2017-09-03 01:35:49.057010: E tensorflow/stream_executor/cuda/cuda_dnn.cc:326] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2017-09-03 01:35:49.068582: E tensorflow/stream_executor/cuda/cuda_dnn.cc:359] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2017-09-03 01:35:49.068780: E tensorflow/stream_executor/cuda/cuda_dnn.cc:326] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2017-09-03 01:35:49.068808: F tensorflow/core/kernels/conv_ops.cc:659] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
Aborted (core dumped)


I am trying to train on my own dataset which has one class and if i define num_class=22 or num_classes=1 or don't define it at all result is this error. Below is my command which i am using to start training


python train_ssd_network.py     --train_dir=${TRAIN_DIR}     --dataset_dir=${DATASET_DIR}     --dataset_name=pascalvoc_2007     --dataset_split_name=train     --model_name=ssd_300_vgg     --checkpoint_path=${CHECKPOINT_PATH}     --checkpoint_model_scope=vgg_16     --checkpoint_exclude_scopes=ssd_300_vgg/conv6,ssd_300_vgg/conv7,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box     --trainable_scopes=ssd_300_vgg/conv6,ssd_300_vgg/conv7,ssd_300_vgg/block8,ssd_300_vgg/block9,ssd_300_vgg/block10,ssd_300_vgg/block11,ssd_300_vgg/block4_box,ssd_300_vgg/block7_box,ssd_300_vgg/block8_box,ssd_300_vgg/block9_box,ssd_300_vgg/block10_box,ssd_300_vgg/block11_box     --save_summaries_secs=60     --save_interval_secs=600     --weight_decay=0.0005     --optimizer=adam     --learning_rate=0.001     --learning_rate_decay_factor=0.94     --batch_size=2 --num_classes=1
