### ISSUE TITLE
caffemodel (512) conversion error 

### ISSUE THREAD

**Issue by jwnsu** [balancap/SSD-Tensorflow#8]
Tried to convert an existing ssd_512_vgg caffemodel file, got following error:
"Traceback (most recent call last):
  File "caffe_to_tensorflow.py", line 64, in <module>
    tf.app.run()
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "caffe_to_tensorflow.py", line 50, in main
    ssd_net.net(img_input, is_training=False)
  File "/home/dsu/ai/stf/nets/ssd_vgg_512.py", line 132, in net
    scope=scope)
  File "/home/dsu/ai/stf/nets/ssd_vgg_512.py", line 452, in ssd_net
    normalizations[i])
  File "/home/dsu/ai/stf/nets/ssd_vgg_300.py", line 419, in ssd_multibox_layer
    tensor_shape(cls_pred, 4)[:-1]+[num_anchors, num_classes])
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2630, in reshape
    name=name)
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/dsu/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Cannot reshape a tensor with 229376 elements to shape [1,64,64,4,21] (344064 elements) for 'ssd_512_vgg/block4_box/Reshape_1' (op: 'Reshape') with input shapes: [1,64,64,56], [5]."

Command line is: "python caffe_to_tensorflow.py --model_name=ssd_512_vgg --num_classes=14 --caffemodel_path=${CAFFE_MODEL}"

Env: ubuntu 16.04.1, tensorflow 1.0.

**Comment by balancap** [comment]
Hello,
My mistake ! I forgot to pass the `num_classes` parameter to the SSD net in caffe to tensorflow script.
Should be fixed now!

**Comment by jwnsu** [comment]
Thanks for quick feedback. Pulled latest code again, it passed previous error point block4 and now reported an error from block7:
"ValueError: Cannot reshape a tensor with 32768 elements to shape [1,32,32,6,4] (24576 elements) for 'ssd_512_vgg/block7_box/Reshape' (op: 'Reshape') with input shapes: [1,32,32,32], [5]."

**Comment by balancap** [comment]
It looks like your architecture is a bit different from the original SSD-512. In particular, the number of anchor boxes on Block 7 is different (seems to 8 and not 6). You may have to adapt the default parameters in `ssd_vgg_512.py` to your configuration.
If you have the `deploy.txt` Caffe file or some Python conf. file, I could have a look at it.

**Comment by jwnsu** [comment]
Hi Paul,

Can you give me your email address? I will send you a link of the deploy
file.

Yes, you are right. I added a ratio to fine-tune for our particular dataset.

Thanks,
Dennis

**Comment by jwnsu** [comment]
only change I made from original was aspect_rations with this line of change:
"aspect_ratios = [[2], [2, 3, 5], [2, 3, 5], [2, 3, 5], [2, 3], [2], [2]]".

**Comment by jwnsu** [comment]
Also I took another model trained with original SSD-512, but with num_classes=14 instead of 21, got following error when running demo from notebook (at line "saver.restore(isess, ckpt_filename)"):
"InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [126] rhs shape= [84]"

It seems it's hard-coded to 21 classes again?

Thanks!

**Comment by balancap** [comment]
Hello, 
when you change the number of classes or/and the aspects ratios, you need to pass update parameters to the SSD object you're creating. That's what I had forgotten in the convertion script. Namelly:
```python
ssd_params = ssd_vgg_512.default_params
ssd_params = ssd_params._replace(num_classes=14)
ssd_net = ssd_vgg_512.SSDNet()
```
Similarly, you need to update the aspects ratios with the one you used:
```python
anchor_ratios=[[2, .5],
                       [2, .5, 3, 1./3, 5, 1./5],
                       [2, .5, 3, 1./3, 5, 1./5],
                       [2, .5, 3, 1./3, 5, 1./5],
                       [2, .5, 3, 1./3, 5, 1./5],
                       [2, .5],
                       [2, .5]],
ssd_params = ssd_params._replace(anchor_ratios=anchor_ratios)
```
Hope this will help!

**Comment by JcmeLs** [comment]
@balancap Hi~How to pass update parameters to my SSD object?
