### ISSUE TITLE
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Assign requires shapes of both tensors to match.

### ISSUE THREAD

**Issue by yongjin120** [balancap/SSD-Tensorflow#88]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Assign requires shapes of both tensors to match. lhs shape= [3,3,256,24] rhs shape= [3,3,256,84]
	 [[Node: save_1/Assign_13 = Assign[T=DT_FLOAT, _class=["loc:@ssd_300_vgg/block11_box/conv_cls/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ssd_300_vgg/block11_box/conv_cls/weights, save_1/RestoreV2_13)]]

Caused by op u'save_1/Assign_13', defined at:
  File "/data2/KYJ/SSD-Tensorflow-master/train_ssd_network.py", line 400, in <module>
    tf.app.run(main=main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/data2/KYJ/SSD-Tensorflow-master/train_ssd_network.py", line 385, in main
    init_fn=tf_utils.get_init_fn(FLAGS),
  File "/data2/KYJ/SSD-Tensorflow-master/tf_utils.py", line 235, in get_init_fn
    ignore_missing_vars=flags.ignore_missing_vars)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 584, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 414, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,256,24] rhs shape= [3,3,256,84]
	 [[Node: save_1/Assign_13 = Assign[T=DT_FLOAT, _class=["loc:@ssd_300_vgg/block11_box/conv_cls/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ssd_300_vgg/block11_box/conv_cls/weights, save_1/RestoreV2_13)]]

Traceback (most recent call last):
  File "/data2/KYJ/SSD-Tensorflow-master/train_ssd_network.py", line 400, in <module>
    tf.app.run(main=main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/data2/KYJ/SSD-Tensorflow-master/train_ssd_network.py", line 393, in main
    sync_optimizer=None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 776, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 788, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 949, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 706, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 264, in prepare_session
    init_fn(sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 586, in callback
    saver.restore(session, model_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,256,24] rhs shape= [3,3,256,84]
	 [[Node: save_1/Assign_13 = Assign[T=DT_FLOAT, _class=["loc:@ssd_300_vgg/block11_box/conv_cls/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ssd_300_vgg/block11_box/conv_cls/weights, save_1/RestoreV2_13)]]

Caused by op u'save_1/Assign_13', defined at:
  File "/data2/KYJ/SSD-Tensorflow-master/train_ssd_network.py", line 400, in <module>
    tf.app.run(main=main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/data2/KYJ/SSD-Tensorflow-master/train_ssd_network.py", line 385, in main
    init_fn=tf_utils.get_init_fn(FLAGS),
  File "/data2/KYJ/SSD-Tensorflow-master/tf_utils.py", line 235, in get_init_fn
    ignore_missing_vars=flags.ignore_missing_vars)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 584, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 414, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,256,24] rhs shape= [3,3,256,84]
	 [[Node: save_1/Assign_13 = Assign[T=DT_FLOAT, _class=["loc:@ssd_300_vgg/block11_box/conv_cls/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ssd_300_vgg/block11_box/conv_cls/weights, save_1/RestoreV2_13)]]

I try train_ssd_network
(ubuntu 14.04, CUDA library libcublas.so.8.0, tensorflow-gpu 1.0.1)

https://github.com/balancap/SSD-Tensorflow/issues/8
I saw issues and i tried under changing.

I changed nets/ssd_vgg_300.py num_classes = 21 -> 6, no_annotation_label = 21->6  
and when I convert a dataset to TFRecords format,
I changed pascalvoc_2007.py       - ( TRAIN_STATISTICS, TEST_STATISTICS, SPLITS_TO_SIZES, 
                                                          NUM_CLASSES, fit my dataset )
                 pascalvoc_common.py - ( VOC_LABELS )

Do I need to change anything?

Is this issue related to ' https://github.com/tensorflow/tensorflow/issues/7838 '

please cheak this issues

**Comment by anilhebbar** [comment]
Seems to me it is somehow taking the checkpoint from the ./logs, even though an alternate checkpoint path mentioned. I have been trying to train a 2 class network and saw a similar issue. Here is a log from the output from the console that looks suspicious:

INFO:tensorflow:Ignoring --checkpoint_path because a checkpoint already exists in ./logs/
 
The logs contained were from the 21 class VOC checkpoint 
On clearing the files in the ./logs, the issue seems to have resolved itself

**Comment by JourneyWoo** [comment]
I have the same q:

    INFO:tensorflow:Error reported to Coordinator: <class 
    'tensorflow.python.framework.errors_impl.InvalidArgumentError'>

**Comment by blacklong28** [comment]
I fixed the problem. when you train you own dataset , if  num_class is not 21 ,you'd better do not use the checkpoint  eg VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt or VGG_VOC0712_SSD_512x512_ft_iter_120000.ckpt or ssd_300_vgg.ckpt . 
you can't fine-tuning existing SSD checkpoints , you'd better train from a new model.
eg.
If the train command is 
```
DATASET_DIR=./tfrecords
TRAIN_DIR=./logs/
CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt
python train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2012 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.0005 \
    --optimizer=adam \
    --learning_rate=0.001 \
    --batch_size=32
```

you can change to 

```
DATASET_DIR=./tfrecords
TRAIN_DIR=./logs/
python train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2012 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.0005 \
    --optimizer=adam \
    --learning_rate=0.001 \
    --batch_size=32
```
It works for me.
Hope can help you .
Good luck.

**Comment by ibunny01** [comment]
@yongjin120 hi, could you please tell me how to change the TRAIN_STATISTICS and TRAIN_STATISTICS？  
The origin code is: 
```python
 29 # (Images, Objects) statistics on every class.
 30 TRAIN_STATISTICS = {
 31     'none': (0, 0),
 32     'aeroplane': (238, 306),
 33     'bicycle': (243, 353),
 34     'bird': (330, 486),
 35     'boat': (181, 290),
 36     'bottle': (244, 505),
 37     'bus': (186, 229),
 38     'car': (713, 1250),
 39     'cat': (337, 376),
 40     'chair': (445, 798),
 41     'cow': (141, 259),
 42     'diningtable': (200, 215),
 43     'dog': (421, 510),
 44     'horse': (287, 362),
 45     'motorbike': (245, 339),
 46     'person': (2008, 4690),
 47     'pottedplant': (245, 514),
 48     'sheep': (96, 257),
 49     'sofa': (229, 248),
 50     'train': (261, 297),
 51     'tvmonitor': (256, 324),
 52     'total': (5011, 12608),
 53 }
 54 TEST_STATISTICS = {
 55     'none': (0, 0),
 56     'aeroplane': (1, 1),
 57     'bicycle': (1, 1),
 58     'bird': (1, 1),
 59     'boat': (1, 1),
 60     'bottle': (1, 1),
 61     'bus': (1, 1),
 62     'car': (1, 1),
 63     'cat': (1, 1),
 64     'chair': (1, 1),
 65     'cow': (1, 1),
 66     'diningtable': (1, 1),
 67     'dog': (1, 1),
 68     'horse': (1, 1),
 69     'motorbike': (1, 1),
 70     'person': (1, 1),
 71     'pottedplant': (1, 1),
 72     'sheep': (1, 1),
 73     'sofa': (1, 1),
 74     'train': (1, 1),
 75     'tvmonitor': (1, 1),
 76     'total': (20, 20),
 77 }
```

I really don't understand the meaning of `(Images, Objects)`,   like 'aeroplane': (238, 306), 238 means there are 238 pictures containing aeroplane, and in the whole training set there are totally 306 aeroplanes? Is that correct? 
But why `TEST_STATISTICS` is (1, 1) all the time?

**Comment by mapeng1995** [comment]
@blacklong617  thanks a lot,your solutions is perfect. But  i have a questions. My dataset only have 5+1 classes which is not the VOC 20+1 classes, and just  60-100 images.When i test the model ,the output in the demo(transform the "INFO:tensorflow:Restoring parameters from ../logs/model.ckpt-
3165\n" to my own model   )is not good .

My questions is how to use the checkpoints on my own dataset, or how to fine-tune?
 
I also notice the original  train code  checkpoint_exclude_scopes , have you fine-tune using this code?

Thanks a lot to read my questions!

**Comment by speculaas** [comment]
Dear All,
Thanks for your help!
Anyone tried to use : 

--checkpoint_exclude_scopes

or 

--trainable_scopes

to avoid layers that related to number of classes?

If so, maybe we can still use pre-trained weight to fine tune for a data set with different number classes?

BR,
JimmyYS
